import {
  Code,
  ImageIcon,
  MessageSquare,
  Mic,
  PenTool,
  Briefcase,
  Brain,
  Video,
  LineChart,
  Database,
  BarChart,
} from "lucide-react"
import type { Tool, Category } from "./types"

// Categories with icons
export const categories: Category[] = [
  {
    name: "Text Generation",
    description: "AI tools for generating text content, including copywriting, content creation, and text completion.",
    icon: <MessageSquare className="h-4 w-4" />,
  },
  {
    name: "Image Generation",
    description: "Create images, art, and designs using AI-powered tools.",
    icon: <ImageIcon className="h-4 w-4" />,
  },
  {
    name: "Coding",
    description: "AI assistants and tools to help with programming, code generation, and debugging.",
    icon: <Code className="h-4 w-4" />,
  },
  {
    name: "Audio & Speech",
    description: "Tools for voice synthesis, transcription, and audio processing.",
    icon: <Mic className="h-4 w-4" />,
  },
  {
    name: "Design",
    description: "AI-powered design tools for UI/UX, graphic design, and creative work.",
    icon: <PenTool className="h-4 w-4" />,
  },
  {
    name: "Productivity",
    description: "Tools to enhance workflow, automate tasks, and improve efficiency.",
    icon: <Briefcase className="h-4 w-4" />,
  },
  {
    name: "Research",
    description: "AI tools for data analysis, research assistance, and knowledge discovery.",
    icon: <Brain className="h-4 w-4" />,
  },
  {
    name: "Video",
    description: "Tools for video generation, editing, and enhancement using AI.",
    icon: <Video className="h-4 w-4" />,
  },
  {
    name: "Analytics",
    description: "AI-powered analytics tools for data insights and business intelligence.",
    icon: <LineChart className="h-4 w-4" />,
  },
  {
    name: "Data Processing",
    description: "Tools for data extraction, transformation, and processing with AI.",
    icon: <Database className="h-4 w-4" />,
  },
  {
    name: "Marketing",
    description: "AI-powered tools for content creation, marketing automation, and campaign optimization.",
    icon: <BarChart className="h-4 w-4" />,
  },
]

// Tools data
export const tools: Tool[] = [
  // Text Generation & Writing Tools
  {
    name: "ChatGPT",
    description: "An AI language model that can engage in conversational dialogue and provide human-like text responses.",
    url: "https://chat.openai.com",
    id: "chatgpt",
    image: "/tool-screenshots/chatgpt.png",
    logo: "/logo/chatgpt.png",
    categories: ["text", "productivity", "research"],
    subcategory: "conversational-ai",
    tags: ["AI", "chatbot", "conversation"],
    rating: 4.8,
    visits: 15000000,
    dateAdded: "2022-11-30",
    isPremium: 'Free',
  },
  {
    name: "GPT-4 (OpenAI API)",
    description: "Advanced language model API for generating human-like text and completing various language tasks.",
    url: "https://openai.com/api",
    id: "gpt-4",
    image: "/tool-screenshots/gpt-4.png",
    logo: "/logo/gpt-4.png",
    categories: ["text", "coding"],
    subcategory: "language-model-api",
    tags: ["AI", "GPT", "API", "language model"],
    rating: 4.9,
    visits: 8000000,
    dateAdded: "2023-03-14",
    isPremium: 'Free',
  },
  {
    name: "Grammarly",
    description: "AI-powered writing assistant that helps you write better by checking grammar, spelling, and style.",
    url: "https://www.grammarly.com",
    id: "grammarly",
    image: "/tool-screenshots/grammarly.png",
    logo: "/logo/grammarly.png",
    categories: ["text", "productivity"],
    subcategory: "grammar",
    tags: ["AI", "grammar", "proofreading", "editing"],
    rating: 4.7,
    visits: 12000000,
    dateAdded: "2020-09-15",
    isPremium: 'Free',
  },
  {
    name: "QuillBot",
    description: "AI-powered paraphrasing tool that helps you rewrite and improve your text while maintaining its meaning.",
    url: "https://quillbot.com",
    id: "quillbot",
    image: "/tool-screenshots/quillbot.png",
    logo: "/logo/quillbot.png",
    categories: ["text", "productivity"],
    subcategory: "paraphrasing",
    tags: ["AI", "paraphrasing", "rewriting", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2021-03-20",
    isPremium: 'Free',
  },
  {
    name: "Rytr",
    description: "AI writing assistant that helps you create high-quality content for various purposes.",
    url: "https://rytr.me",
    id: "rytr",
    image: "/tool-screenshots/rytr.png",
    logo: "/logo/rytr.png",
    categories: ["text", "productivity"],
    subcategory: "writing-assistant",
    tags: ["AI", "writing", "content", "assistant"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-04-15",
    isPremium: 'Free',
  },
  {
    name: "ProWritingAid",
    description: "Comprehensive writing tool that helps you improve your writing style, grammar, and readability.",
    url: "https://prowritingaid.com",
    id: "prowritingaid",
    image: "/tool-screenshots/prowritingaid.png",
    logo: "/logo/prowritingaid.png",
    categories: ["text", "productivity"],
    subcategory: "style-editing",
    tags: ["AI", "style", "editing", "readability"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-06-15",
    isPremium: 'Free',
  },
  {
    name: "Hemingway App",
    description: "AI-powered writing tool that helps you write clear, concise, and readable content.",
    url: "https://hemingwayapp.com",
    id: "hemingway-app",
    image: "/tool-screenshots/hemingway-app.png",
    logo: "/logo/hemingway-app.png",
    categories: ["text", "productivity"],
    subcategory: "readability",
    tags: ["AI", "readability", "writing", "style"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-20",
    isPremium: 'Free',
  },

  // Marketing & Content Tools
  {
    name: "Jasper (formerly Jarvis)",
    description: "AI content creation & copywriting platform.",
    url: "https://www.jasper.ai",
    id: "jasper",
    image: "/tool-screenshots/jasper.png",
    logo: "/logo/jasper.png",
    categories: ["marketing"],
    subcategory: "content-creation",
    tags: ["AI", "content", "copywriting"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2021-01-15",
    isPremium: 'Free',
  },
  {
    name: "Copy.ai",
    description: "AI-powered content and marketing copy generation platform.",
    url: "https://www.copy.ai",
    id: "copy-ai",
    image: "/tool-screenshots/copy-ai.png",
    logo: "/logo/copy-ai.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2021-02-15",
    isPremium: 'Free',
  },
  {
    name: "HubSpot",
    description: "CRM & marketing with AI prediction & automation platform.",
    url: "https://www.hubspot.com",
    id: "hubspot",
    image: "/tool-screenshots/hubspot.png",
    logo: "/logo/hubspot.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "automation"],
    rating: 4.6,
    visits: 20000,
    dateAdded: "2023-06-15",
    isPremium: 'Free',
  },
  {
    name: "Salesforce Einstein",
    description: "AI-powered CRM & marketing tools platform.",
    url: "https://www.salesforce.com/products/einstein/overview",
    id: "salesforce-einstein",
    image: "/tool-screenshots/salesforce-einstein.png",
    logo: "/logo/salesforce-einstein.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "predictive analytics"],
    rating: 4.7,
    visits: 18000,
    dateAdded: "2023-07-15",
    isPremium: 'Free',
  },
  {
    name: "Synthesia",
    description: "AI video creators for marketing platform.",
    url: "https://www.synthesia.io",
    id: "synthesia",
    image: "/tool-screenshots/synthesia.png",
    logo: "/logo/synthesia.png",
    categories: ["marketing"],
    subcategory: "video-creation",
    tags: ["AI", "video", "marketing"],
    rating: 4.6,
    visits: 250000,
    dateAdded: "2022-03-15",
    isPremium: 'Free',
  },
  {
    name: "Lumen5",
    description: "AI social media video content creation platform.",
    url: "https://lumen5.com",
    id: "lumen5",
    image: "/tool-screenshots/lumen5.png",
    logo: "/logo/lumen5.png",
    categories: ["marketing"],
    subcategory: "video-content",
    tags: ["AI", "video", "social media"],
    rating: 4.5,
    visits: 300000,
    dateAdded: "2022-02-15",
    isPremium: 'Free',
  },

  // Productivity & Organization Tools
  {
    name: "Mem",
    description: "AI-powered note organization and intelligent retrieval platform.",
    url: "https://mem.ai",
    id: "mem",
    image: "/tool-screenshots/mem.png",
    logo: "/logo/mem.png",
    categories: ["productivity"],
    subcategory: "note-organization",
    tags: ["AI", "notes", "organization"],
    rating: 4.1,
    visits: 3000,
    dateAdded: "2026-11-15",
    isPremium: 'Free',
  },
  {
    name: "Hugo AI",
    description: "Knowledge management and AI writing assistant.",
    url: "https://hugo.ai",
    id: "hugo-ai",
    image: "/tool-screenshots/hugo-ai.png",
    logo: "/logo/hugo-ai.png",
    categories: ["productivity"],
    subcategory: "knowledge-management",
    tags: ["AI", "knowledge", "writing"],
    rating: 4.3,
    visits: 6000,
    dateAdded: "2026-07-15",
    isPremium: 'Free',
  },
  {
    name: "AI Dungeon",
    description: "Storytelling and creative writing AI for entertainment and inspiration.",
    url: "https://aidungeon.io",
    id: "ai-dungeon",
    image: "/tool-screenshots/ai-dungeon.png",
    logo: "/logo/ai-dungeon.png",
    categories: ["productivity"],
    subcategory: "creative-writing",
    tags: ["AI", "storytelling", "creativity"],
    rating: 4.0,
    visits: 10000,
    dateAdded: "2026-03-15",
    isPremium: 'Free',
  },

  // Image Generation & Creative Tools
  {
    name: "Stable Diffusion",
    description: "Open-source AI model for generating high-quality images from text descriptions.",
    url: "https://stability.ai",
    id: "stable-diffusion",
    image: "/tool-screenshots/stable-diffusion.png",
    logo: "/logo/stable-diffusion.png",
    categories: ["image"],
    subcategory: "open-source",
    tags: ["AI", "open-source", "art", "creative"],
    rating: 4.5,
    visits: 6000000,
    dateAdded: "2022-08-22",
    isPremium: 'Free',
  },
  {
    name: "Adobe Firefly",
    description: "Adobe's AI-powered tool for creating creative assets and image design.",
    url: "https://firefly.adobe.com",
    id: "adobe-firefly",
    image: "/tool-screenshots/adobe-firefly.png",
    logo: "/logo/adobe-firefly.png",
    categories: ["image", "design"],
    subcategory: "creative-assets",
    tags: ["AI", "Adobe", "graphic design"],
    rating: 4.7,
    visits: 5000000,
    dateAdded: "2023-03-21",
    isPremium: 'Free',
  },
  {
    name: "Canva AI",
    description: "AI-powered graphic design platform for creating professional images and templates.",
    url: "https://canva.com",
    id: "canva-ai",
    image: "/tool-screenshots/canva-ai.png",
    logo: "/logo/canva-ai.png",
    categories: ["image", "design"],
    subcategory: "graphic-design",
    tags: ["AI", "design", "graphics", "templates"],
    rating: 4.6,
    visits: 8000000,
    dateAdded: "2023-01-15",
    isPremium: 'Free',
  },
  {
    name: "Artbreeder",
    description: "AI platform for genetic image merging and creative image generation.",
    url: "https://artbreeder.com",
    id: "artbreeder",
    image: "/tool-screenshots/artbreeder.png",
    logo: "/logo/artbreeder.png",
    categories: ["image"],
    subcategory: "image-blending",
    tags: ["AI", "image blending", "art"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-08-01",
    isPremium: 'Free',
  },
  {
    name: "Runway ML",
    description: "AI-powered video editing and generation platform for creative professionals.",
    url: "https://runwayml.com",
    id: "runway-ml",
    image: "/tool-screenshots/runway-ml.png",
    logo: "/logo/runway-ml.png",
    categories: ["video", "design"],
    subcategory: "video-generation",
    tags: ["AI", "video", "creative", "editing"],
    rating: 4.6,
    visits: 2200000,
    dateAdded: "2018-12-01",
    isPremium: 'Free',
  },
  {
    name: "NightCafe Studio",
    description: "AI-powered platform for artistic image generation and style transfer.",
    url: "https://nightcafe.studio",
    id: "nightcafe-studio",
    image: "/tool-screenshots/nightcafe-studio.png",
    logo: "/logo/nightcafe-studio.png",
    categories: ["image"],
    subcategory: "artistic",
    tags: ["AI", "art", "style transfer"],
    rating: 4.2,
    visits: 1200000,
    dateAdded: "2021-12-01",
    isPremium: 'Free',
  },
  {
    name: "This Person Does Not Exist",
    description: "AI-generated realistic human faces using GAN technology.",
    url: "https://thispersondoesnotexist.com",
    id: "this-person-does-not-exist",
    image: "/tool-screenshots/this-person-does-not-exist.png",
    logo: "/logo/this-person-does-not-exist.png",
    categories: ["image"],
    subcategory: "face-generation",
    tags: ["AI", "faces", "realism"],
    rating: 4.4,
    visits: 3000000,
    dateAdded: "2020-12-01",
    isPremium: 'Free',
  },
] 