import React from 'react'
import {
  Code,
  ImageIcon,
  MessageSquare,
  Mic,
  PenTool,
  Briefcase,
  Brain,
  Video,
  LineChart,
  Database,
  BarChart,
} from "lucide-react"
import type { Tool, Category } from "./types"

// Categories with icons
export const categories: Category[] = [
  {
    name: "Text Generation",
    description: "AI tools for generating text content, including copywriting, content creation, and text completion.",
    icon: <MessageSquare className="h-4 w-4" />,
  },
  {
    name: "Image Generation",
    description: "Create images, art, and designs using AI-powered tools.",
    icon: <ImageIcon className="h-4 w-4" />,
  },
  {
    name: "Coding",
    description: "AI assistants and tools to help with programming, code generation, and debugging.",
    icon: <Code className="h-4 w-4" />,
  },
  {
    name: "Audio & Speech",
    description: "Tools for voice synthesis, transcription, and audio processing.",
    icon: <Mic className="h-4 w-4" />,
  },
  {
    name: "Design",
    description: "AI-powered design tools for UI/UX, graphic design, and creative work.",
    icon: <PenTool className="h-4 w-4" />,
  },
  {
    name: "Productivity",
    description: "Tools to enhance workflow, automate tasks, and improve efficiency.",
    icon: <Briefcase className="h-4 w-4" />,
  },
  {
    name: "Research",
    description: "AI tools for data analysis, research assistance, and knowledge discovery.",
    icon: <Brain className="h-4 w-4" />,
  },
  {
    name: "Video",
    description: "Tools for video generation, editing, and enhancement using AI.",
    icon: <Video className="h-4 w-4" />,
  },
  {
    name: "Analytics",
    description: "AI-powered analytics tools for data insights and business intelligence.",
    icon: <LineChart className="h-4 w-4" />,
  },
  {
    name: "Data Processing",
    description: "Tools for data extraction, transformation, and processing with AI.",
    icon: <Database className="h-4 w-4" />,
  },
  {
    name: "Marketing",
    description: "AI-powered tools for content creation, marketing automation, and campaign optimization.",
    icon: <BarChart className="h-4 w-4" />,
  },
]

// Combined tools data
export const tools: Tool[] = [
  {
    name: "ChatGPT",
    description: "An AI language model that can engage in conversational dialogue and provide human-like text responses.",
    url: "https://chat.openai.com",
    id: "chatgpt",
    image: "/tool-screenshots/chatgpt.png",
    logo: "/logo/chatgpt.png",
    categories: ["text", "productivity", "research"],
    subcategory: "conversational-ai",
    tags: ["AI", "chatbot", "conversation"],
    rating: 4.8,
    visits: 15000000,
    dateAdded: "2022-11-30",
    isPremium: 'Free',
  },
  {
    name: "GPT-4 (OpenAI API)",
    description: "Advanced language model API for generating human-like text and completing various language tasks.",
    url: "https://openai.com/api",
    id: "gpt-4",
    image: "/tool-screenshots/gpt-4.png",
    logo: "/logo/gpt-4.png",
    categories: ["text", "coding"],
    subcategory: "language-model-api",
    tags: ["AI", "GPT", "API", "language model"],
    rating: 4.9,
    visits: 8000000,
    dateAdded: "2023-03-14",
    isPremium: 'Free',
  },
  {
    name: "GPT-3 (OpenAI API)",
    description: "Powerful language model API for text generation and natural language processing tasks.",
    url: "https://openai.com/api",
    id: "gpt-3",
    image: "/tool-screenshots/gpt-3.png",
    logo: "/logo/gpt-3.png",
    categories: ["text", "coding"],
    subcategory: "language-model-api",
    tags: ["AI", "GPT", "API", "language model"],
    rating: 4.7,
    visits: 6000000,
    dateAdded: "2020-06-11",
    isPremium: 'Free',
  },
  {
    name: "Jasper (formerly Jarvis)",
    description: "AI content creation & copywriting platform.",
    url: "https://www.jasper.ai",
    id: "jasper",
    image: "/tool-screenshots/jasper.png",
    logo: "/logo/jasper.png",
    categories: ["marketing"],
    subcategory: "content-creation",
    tags: ["AI", "content", "copywriting"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2021-01-15",
    isPremium: 'Free',
  },
  {
    name: "Conversion.ai (Jasper AI)",
    description: "AI marketing & sales copy generation platform.",
    url: "https://www.conversion.ai",
    id: "conversion-ai",
    image: "/tool-screenshots/conversion-ai.png",
    logo: "/logo/conversion-ai.png",
    categories: ["marketing"],
    subcategory: "sales-copy",
    tags: ["AI", "marketing", "sales"],
    rating: 4.6,
    visits: 600000,
    dateAdded: "2021-10-15",
    isPremium: 'Free',
  },
  {
    name: "INK (by Ink for All)",
    description: "AI-driven content optimization & SEO platform.",
    url: "https://inkforall.com",
    id: "ink",
    image: "/tool-screenshots/ink.png",
    logo: "/logo/ink.png",
    categories: ["marketing"],
    subcategory: "content-optimization",
    tags: ["AI", "SEO", "content"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2021-11-15",
    isPremium: 'Free',
  },
  {
    name: "CopySmith",
    description: "AI content generation for marketing platform.",
    url: "https://copysmith.ai",
    id: "copysmith",
    image: "/tool-screenshots/copysmith.png",
    logo: "/logo/copysmith.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.3,
    visits: 400000,
    dateAdded: "2021-12-15",
    isPremium: 'Free',
  },
  {
    name: "Copyscape",
    description: "AI-powered plagiarism detection & content validation platform.",
    url: "https://www.copyscape.com",
    id: "copyscape",
    image: "/tool-screenshots/copyscape.png",
    logo: "/logo/copyscape.png",
    categories: ["marketing"],
    subcategory: "content-validation",
    tags: ["AI", "plagiarism", "content"],
    rating: 4.4,
    visits: 350000,
    dateAdded: "2022-01-15",
    isPremium: 'Free',
  },
  {
    name: "Grammarly",
    description: "AI-powered writing assistant that helps you write better by checking grammar, spelling, and style.",
    url: "https://www.grammarly.com",
    id: "grammarly",
    image: "/tool-screenshots/grammarly.png",
    logo: "/logo/grammarly.png",
    categories: ["text", "productivity"],
    subcategory: "grammar",
    tags: ["AI", "grammar", "proofreading", "editing"],
    rating: 4.7,
    visits: 12000000,
    dateAdded: "2020-09-15",
    isPremium: 'Free',
  },
  {
    name: "QuillBot",
    description: "AI-powered paraphrasing tool that helps you rewrite and improve your text while maintaining its meaning.",
    url: "https://quillbot.com",
    id: "quillbot",
    image: "/tool-screenshots/quillbot.png",
    logo: "/logo/quillbot.png",
    categories: ["text", "productivity"],
    subcategory: "paraphrasing",
    tags: ["AI", "paraphrasing", "rewriting", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2021-03-20",
    isPremium: 'Free',
  },
  {
    name: "Rytr",
    description: "AI writing assistant that helps you create high-quality content for various purposes.",
    url: "https://rytr.me",
    id: "rytr",
    image: "/tool-screenshots/rytr.png",
    logo: "/logo/rytr.png",
    categories: ["text", "productivity"],
    subcategory: "writing-assistant",
    tags: ["AI", "writing", "content", "assistant"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-04-15",
    isPremium: 'Free',
  },
  {
    name: "ProWritingAid",
    description: "Comprehensive writing tool that helps you improve your writing style, grammar, and readability.",
    url: "https://prowritingaid.com",
    id: "prowritingaid",
    image: "/tool-screenshots/prowritingaid.png",
    logo: "/logo/prowritingaid.png",
    categories: ["text", "productivity"],
    subcategory: "style-editing",
    tags: ["AI", "style", "editing", "readability"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-06-15",
    isPremium: 'Free',
  },
  {
    name: "Hemingway App",
    description: "AI-powered writing tool that helps you write clear, concise, and readable content.",
    url: "https://hemingwayapp.com",
    id: "hemingway-app",
    image: "/tool-screenshots/hemingway-app.png",
    logo: "/logo/hemingway-app.png",
    categories: ["text", "productivity"],
    subcategory: "readability",
    tags: ["AI", "readability", "writing", "style"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-20",
    isPremium: 'Free',
  },
  {
    name: "Copy.ai",
    description: "AI-powered content and marketing copy generation platform.",
    url: "https://www.copy.ai",
    id: "copy-ai",
    image: "/tool-screenshots/copy-ai.png",
    logo: "/logo/copy-ai.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2021-02-15",
    isPremium: 'Free',
  },
  {
    name: "HubSpot",
    description: "CRM & marketing with AI prediction & automation platform.",
    url: "https://www.hubspot.com",
    id: "hubspot",
    image: "/tool-screenshots/hubspot.png",
    logo: "/logo/hubspot.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "automation"],
    rating: 4.6,
    visits: 20000,
    dateAdded: "2023-06-15",
    isPremium: 'Free',
  },
  {
    name: "Salesforce Einstein",
    description: "AI-powered CRM & marketing tools platform.",
    url: "https://www.salesforce.com/products/einstein/overview",
    id: "salesforce-einstein",
    image: "/tool-screenshots/salesforce-einstein.png",
    logo: "/logo/salesforce-einstein.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "predictive analytics"],
    rating: 4.7,
    visits: 18000,
    dateAdded: "2023-07-15",
    isPremium: 'Free',
  },
  {
    name: "Synthesia",
    description: "AI video creators for marketing platform.",
    url: "https://www.synthesia.io",
    id: "synthesia",
    image: "/tool-screenshots/synthesia.png",
    logo: "/logo/synthesia.png",
    categories: ["marketing"],
    subcategory: "video-creation",
    tags: ["AI", "video", "marketing"],
    rating: 4.6,
    visits: 250000,
    dateAdded: "2022-03-15",
    isPremium: 'Free',
  },
  {
    name: "Lumen5",
    description: "AI social media video content creation platform.",
    url: "https://lumen5.com",
    id: "lumen5",
    image: "/tool-screenshots/lumen5.png",
    logo: "/logo/lumen5.png",
    categories: ["marketing"],
    subcategory: "video-content",
    tags: ["AI", "video", "social media"],
    rating: 4.5,
    visits: 300000,
    dateAdded: "2022-02-15",
    isPremium: 'Free',
  },
  {
    name: "Mem",
    description: "AI-powered note organization and intelligent retrieval platform.",
    url: "https://mem.ai",
    id: "mem",
    image: "/tool-screenshots/mem.png",
    logo: "/logo/mem.png",
    categories: ["productivity"],
    subcategory: "note-organization",
    tags: ["AI", "notes", "organization"],
    rating: 4.1,
    visits: 3000,
    dateAdded: "2026-11-15",
    isPremium: 'Free',
  },
  {
    name: "Hugo AI",
    description: "Knowledge management and AI writing assistant.",
    url: "https://hugo.ai",
    id: "hugo-ai",
    image: "/tool-screenshots/hugo-ai.png",
    logo: "/logo/hugo-ai.png",
    categories: ["productivity"],
    subcategory: "knowledge-management",
    tags: ["AI", "knowledge", "writing"],
    rating: 4.3,
    visits: 6000,
    dateAdded: "2026-07-15",
    isPremium: 'Free',
  },
  {
    name: "AI Dungeon",
    description: "Storytelling and creative writing AI for entertainment and inspiration.",
    url: "https://aidungeon.io",
    id: "ai-dungeon",
    image: "/tool-screenshots/ai-dungeon.png",
    logo: "/logo/ai-dungeon.png",
    categories: ["productivity"],
    subcategory: "creative-writing",
    tags: ["AI", "storytelling", "creativity"],
    rating: 4.0,
    visits: 10000,
    dateAdded: "2026-03-15",
    isPremium: 'Free',
  },
  {
    name: "Stable Diffusion",
    description: "Open-source AI model for generating high-quality images from text descriptions.",
    url: "https://stability.ai",
    id: "stable-diffusion",
    image: "/tool-screenshots/stable-diffusion.png",
    logo: "/logo/stable-diffusion.png",
    categories: ["image"],
    subcategory: "open-source",
    tags: ["AI", "open-source", "art", "creative"],
    rating: 4.5,
    visits: 6000000,
    dateAdded: "2022-08-22",
    isPremium: 'Free',
  },
  {
    name: "Adobe Firefly",
    description: "Adobe's AI-powered tool for creating creative assets and image design.",
    url: "https://firefly.adobe.com",
    id: "adobe-firefly",
    image: "/tool-screenshots/adobe-firefly.png",
    logo: "/logo/adobe-firefly.png",
    categories: ["image", "design"],
    subcategory: "creative-assets",
    tags: ["AI", "Adobe", "graphic design"],
    rating: 4.7,
    visits: 5000000,
    dateAdded: "2023-03-21",
    isPremium: 'Free',
  },
  {
    name: "Canva AI",
    description: "AI-powered graphic design platform for creating professional images and templates.",
    url: "https://canva.com",
    id: "canva-ai",
    image: "/tool-screenshots/canva-ai.png",
    logo: "/logo/canva-ai.png",
    categories: ["image", "design"],
    subcategory: "graphic-design",
    tags: ["AI", "design", "graphics", "templates"],
    rating: 4.6,
    visits: 8000000,
    dateAdded: "2023-01-15",
    isPremium: 'Free',
  },
  {
    name: "Artbreeder",
    description: "AI platform for genetic image merging and creative image generation.",
    url: "https://artbreeder.com",
    id: "artbreeder",
    image: "/tool-screenshots/artbreeder.png",
    logo: "/logo/artbreeder.png",
    categories: ["image"],
    subcategory: "image-blending",
    tags: ["AI", "image blending", "art"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-08-01",
    isPremium: 'Free',
  },
  {
    name: "Runway ML",
    description: "AI-powered video editing and generation platform for creative professionals.",
    url: "https://runwayml.com",
    id: "runway-ml",
    image: "/tool-screenshots/runway-ml.png",
    logo: "/logo/runway-ml.png",
    categories: ["video", "design"],
    subcategory: "video-generation",
    tags: ["AI", "video", "creative", "editing"],
    rating: 4.6,
    visits: 2200000,
    dateAdded: "2018-12-01",
    isPremium: 'Free',
  },
  {
    name: "NightCafe Studio",
    description: "AI-powered platform for artistic image generation and style transfer.",
    url: "https://nightcafe.studio",
    id: "nightcafe-studio",
    image: "/tool-screenshots/nightcafe-studio.png",
    logo: "/logo/nightcafe-studio.png",
    categories: ["image"],
    subcategory: "artistic",
    tags: ["AI", "art", "style transfer"],
    rating: 4.2,
    visits: 1200000,
    dateAdded: "2021-12-01",
    isPremium: 'Free',
  },
  {
    name: "This Person Does Not Exist",
    description: "AI-generated realistic human faces using GAN technology.",
    url: "https://thispersondoesnotexist.com",
    id: "this-person-does-not-exist",
    image: "/tool-screenshots/this-person-does-not-exist.png",
    logo: "/logo/this-person-does-not-exist.png",
    categories: ["image"],
    subcategory: "face-generation",
    tags: ["AI", "faces", "realism"],
    rating: 4.4,
    visits: 3000000,
    dateAdded: "2020-12-01",
    isPremium: 'Free',
  },
  {
    name: "Lensa AI",
    description: "AI-powered portrait and photo editing app.",
    url: "https://lensa-ai.com",
    id: "lensa-ai",
    image: "/tool-screenshots/lensa-ai.png",
    logo: "/logo/lensa-ai.png",
    categories: ["image"],
    subcategory: "portrait",
    tags: ["AI", "portrait", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
  {
    name: "Toongineer Cartoonizer",
    description: "AI tool for transforming photos into cartoon-style images.",
    url: "https://toongineer.com",
    id: "toongineer-cartoonizer",
    image: "/tool-screenshots/toongineer-cartoonizer.png",
    logo: "/logo/toongineer-cartoonizer.png",
    categories: ["image"],
    subcategory: "cartoon",
    tags: ["AI", "cartoon", "stylization"],
    rating: 4.2,
    visits: 1000000,
    dateAdded: "2022-10-01",
    isPremium: 'Free'
  },
  {
    name: "Piggy.ai",
    description: "AI platform for comedy and creative image generation.",
    url: "https://piggy.ai",
    id: "piggy-ai",
    image: "/tool-screenshots/piggy-ai.png",
    logo: "/logo/piggy-ai.png",
    categories: ["image"],
    subcategory: "comedy",
    tags: ["AI", "humorous", "creative"],
    rating: 4.1,
    visits: 800000,
    dateAdded: "2022-07-01",
    isPremium: 'Free'
  },
  {
    name: "StarryAI",
    description: "AI platform for generating art and NFTs.",
    url: "https://starryai.com",
    id: "starryai",
    image: "/tool-screenshots/starryai.png",
    logo: "/logo/starryai.png",
    categories: ["image"],
    subcategory: "nft-art",
    tags: ["AI", "art", "NFTs", "creativity"],
    rating: 4.4,
    visits: 2000000,
    dateAdded: "2022-06-01",
    isPremium: 'Free'
  },
  {
    name: "AI Painter",
    description: "AI tool for creating realistic and creative paintings.",
    url: "https://ai-painter.com",
    id: "ai-painter",
    image: "/tool-screenshots/ai-painter.png",
    logo: "/logo/ai-painter.png",
    categories: ["image"],
    subcategory: "painting",
    tags: ["AI", "painting", "art"],
    rating: 4.2,
    visits: 1200000,
    dateAdded: "2022-05-01",
    isPremium: 'Free'
  },
  {
    name: "Jasper Art",
    description: "AI tool for generating content marketing images.",
    url: "https://jasper.ai/art",
    id: "jasper-art",
    image: "/tool-screenshots/jasper-art.png",
    logo: "/logo/jasper-art.png",
    categories: ["image", "marketing"],
    subcategory: "marketing",
    tags: ["AI", "marketing", "content", "art"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2022-04-01",
    isPremium: 'Free'
  },
  {
    name: "Craiyon (formerly DALL·E Mini)",
    description: "Quick and accessible text-to-image generation tool.",
    url: "https://craiyon.com",
    id: "craiyon",
    image: "/tool-screenshots/craiyon.png",
    logo: "/logo/craiyon.png",
    categories: ["image"],
    subcategory: "quick-generation",
    tags: ["AI", "art", "quick generation"],
    rating: 4.1,
    visits: 3000000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
  {
    name: "DeepAngel",
    description: "AI tool for removing objects and editing images.",
    url: "https://deepangel.com",
    id: "deepangel",
    image: "/tool-screenshots/deepangel.png",
    logo: "/logo/deepangel.png",
    categories: ["image"],
    subcategory: "editing",
    tags: ["AI", "editing", "removal"],
    rating: 4.0,
    visits: 900000,
    dateAdded: "2022-02-01",
    isPremium: 'Free'
  },
  {
    name: "Deep Nostalgia",
    description: "AI tool for animating photos from still images.",
    url: "https://myheritage.com/deep-nostalgia",
    id: "deep-nostalgia",
    image: "/tool-screenshots/deep-nostalgia.png",
    logo: "/logo/deep-nostalgia.png",
    categories: ["image", "video"],
    subcategory: "animation",
    tags: ["AI", "animation", "photo"],
    rating: 4.3,
    visits: 2500000,
    dateAdded: "2022-01-01",
    isPremium: 'Free'
  },
  {
    name: "FaceApp",
    description: "AI-powered app for facial transformations and edits.",
    url: "https://faceapp.com",
    id: "faceapp",
    image: "/tool-screenshots/faceapp.png",
    logo: "/logo/faceapp.png",
    categories: ["image"],
    subcategory: "face-editing",
    tags: ["AI", "faces", "editing"],
    rating: 4.4,
    visits: 3500000,
    dateAdded: "2021-12-01",
    isPremium: 'Free'
  },
  {
    name: "GitHub Copilot",
    description: "AI pair programmer that helps you write better code faster.",
    url: "https://github.com/features/copilot",
    id: "github-copilot",
    image: "/tool-screenshots/github-copilot.png",
    logo: "/logo/github-copilot.png",
    categories: ["coding"],
    subcategory: "code-assistant",
    tags: ["AI", "coding", "programming", "developer"],
    rating: 4.6,
    visits: 3500000,
    dateAdded: "2021-10-27",
    isPremium: 'Free'
  },
  {
    name: "Amazon CodeWhisperer",
    description: "AI-powered code generation tool integrated with AWS services.",
    url: "https://aws.amazon.com/codewhisperer",
    id: "amazon-codewhisperer",
    image: "/tool-screenshots/amazon-codewhisperer.png",
    logo: "/logo/amazon-codewhisperer.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "code", "automation", "AWS"],
    rating: 4.5,
    visits: 3000000,
    dateAdded: "2022-06-23",
    isPremium: 'Free'
  },
  {
    name: "Tabnine",
    description: "AI code completion tool that helps developers write code faster and more efficiently.",
    url: "https://www.tabnine.com",
    id: "tabnine",
    image: "/tool-screenshots/tabnine.png",
    logo: "/logo/tabnine.png",
    categories: ["coding"],
    subcategory: "code-completion",
    tags: ["AI", "coding", "programming", "developer"],
    rating: 4.4,
    visits: 2000000,
    dateAdded: "2018-11-15",
    isPremium: 'Free'
  },
  {
    name: "Replit Ghostwriter",
    description: "AI coding assistant integrated directly into the Replit IDE for seamless development.",
    url: "https://replit.com/ghostwriter",
    id: "replit-ghostwriter",
    image: "/tool-screenshots/replit-ghostwriter.png",
    logo: "/logo/replit-ghostwriter.png",
    categories: ["coding"],
    subcategory: "ide-integration",
    tags: ["AI", "IDE", "code generation", "collaboration"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2023-01-10",
    isPremium: 'Free'
  },
  {
    name: "DeepCode (Snyk Code)",
    description: "AI-driven code review and bug detection platform for improved code quality.",
    url: "https://snyk.io/product/snyk-code",
    id: "deepcode",
    image: "/tool-screenshots/deepcode.png",
    logo: "/logo/deepcode.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "bug fixing"],
    rating: 4.5,
    visits: 1800000,
    dateAdded: "2021-08-20",
    isPremium: 'Free'
  },
  {
    name: "Kite",
    description: "AI-powered code completion and documentation tool for developers.",
    url: "https://kite.com",
    id: "kite",
    image: "/tool-screenshots/kite.png",
    logo: "/logo/kite.png",
    categories: ["coding"],
    subcategory: "code-assistance",
    tags: ["AI", "autocompletion", "documentation"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-15",
    isPremium: 'Free'
  },
  {
    name: "Codeium",
    description: "Real-time AI code completion tool for faster and more efficient coding.",
    url: "https://codeium.com",
    id: "codeium",
    image: "/tool-screenshots/codeium.png",
    logo: "/logo/codeium.png",
    categories: ["coding"],
    subcategory: "code-autocompletion",
    tags: ["AI", "IDE", "developer tools"],
    rating: 4.4,
    visits: 1200000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
  {
    name: "Sourcegraph",
    description: "AI-enhanced code search and intelligence platform for better code navigation.",
    url: "https://sourcegraph.com",
    id: "sourcegraph",
    image: "/tool-screenshots/sourcegraph.png",
    logo: "/logo/sourcegraph.png",
    categories: ["coding"],
    subcategory: "code-search",
    tags: ["AI", "codebase", "navigation"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2021-11-15",
    isPremium: 'Free'
  },
  {
    name: "Cogram",
    description: "AI-powered SQL code generation and analytics platform.",
    url: "https://cogram.com",
    id: "cogram",
    image: "/tool-screenshots/cogram.png",
    logo: "/logo/cogram.png",
    categories: ["coding", "data"],
    subcategory: "sql-generation",
    tags: ["AI", "SQL", "data analysis"],
    rating: 4.3,
    visits: 900000,
    dateAdded: "2022-02-15",
    isPremium: 'Free'
  },
  {
    name: "PolyCoder",
    description: "Open-source large-scale code generator for various programming languages.",
    url: "https://github.com/VHellendoorn/Code-LMs",
    id: "polycoder",
    image: "/tool-screenshots/polycoder.png",
    logo: "/logo/polycoder.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "open-source", "models"],
    rating: 4.1,
    visits: 800000,
    dateAdded: "2022-04-01",
    isPremium: 'Free'
  },
  {
    name: "OpenAI Codex",
    description: "Natural language to code generation API powered by GPT-3.",
    url: "https://openai.com/blog/openai-codex",
    id: "openai-codex",
    image: "/tool-screenshots/openai-codex.png",
    logo: "/logo/openai-codex.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "API", "GPT-3", "code synthesis"],
    rating: 4.7,
    visits: 3500000,
    dateAdded: "2021-08-10",
    isPremium: 'Free'
  },
  {
    name: "WizardCoder",
    description: "Cloud-based AI coding helper for developers.",
    url: "https://wizardcoder.com",
    id: "wizardcoder",
    image: "/tool-screenshots/wizardcoder.png",
    logo: "/logo/wizardcoder.png",
    categories: ["coding"],
    subcategory: "cloud-coding",
    tags: ["AI", "cloud", "development tools"],
    rating: 4.2,
    visits: 700000,
    dateAdded: "2022-05-15",
    isPremium: 'Free'
  },
  {
    name: "DeepDev",
    description: "AI-powered debugging and code correction tool.",
    url: "https://deepdev.io",
    id: "deepdev",
    image: "/tool-screenshots/deepdev.png",
    logo: "/logo/deepdev.png",
    categories: ["coding"],
    subcategory: "debugging",
    tags: ["AI", "debugging", "troubleshooting"],
    rating: 4.3,
    visits: 600000,
    dateAdded: "2022-06-01",
    isPremium: 'Free'
  },
  {
    name: "GPT-4 Code Interpreter",
    description: "Advanced code analysis and generation using GPT-4.",
    url: "https://openai.com/gpt-4",
    id: "gpt-4-code-interpreter",
    image: "/tool-screenshots/gpt-4-code-interpreter.png",
    logo: "/logo/gpt-4-code-interpreter.png",
    categories: ["coding"],
    subcategory: "code-analysis",
    tags: ["AI", "GPT-4", "code", "interpretation"],
    rating: 4.8,
    visits: 4000000,
    dateAdded: "2023-03-14",
    isPremium: 'Free'
  },
  {
    name: "Microsoft Turing",
    description: "Enterprise AI development models for large-scale applications.",
    url: "https://www.microsoft.com/en-us/ai/turing",
    id: "microsoft-turing",
    image: "/tool-screenshots/microsoft-turing.png",
    logo: "/logo/microsoft-turing.png",
    categories: ["coding"],
    subcategory: "enterprise-ai",
    tags: ["AI", "enterprise", "models"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2022-07-01",
    isPremium: 'Free'
  },
  {
    name: "CodeT5",
    description: "Multi-language code understanding and generation model.",
    url: "https://github.com/salesforce/CodeT5",
    id: "codet5",
    image: "/tool-screenshots/codet5.png",
    logo: "/logo/codet5.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "T5", "models"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2022-08-15",
    isPremium: 'Free'
  },
  {
    name: "Codex Playground",
    description: "Interactive environment for experimenting with AI code models.",
    url: "https://openai.com/blog/openai-codex",
    id: "codex-playground",
    image: "/tool-screenshots/codex-playground.png",
    logo: "/logo/codex-playground.png",
    categories: ["coding"],
    subcategory: "experimentation",
    tags: ["AI", "GPT", "playground"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2022-09-01",
    isPremium: 'Free'
  },
  {
    name: "AI4Code",
    description: "AI platform for automated code reviews and suggestions.",
    url: "https://ai4code.com",
    id: "ai4code",
    image: "/tool-screenshots/ai4code.png",
    logo: "/logo/ai4code.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "QA"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2022-10-01",
    isPremium: 'Free'
  },
  {
    name: "ChatCode",
    description: "Interactive AI coding chatbot for developer support.",
    url: "https://chatcode.ai",
    id: "chatcode",
    image: "/tool-screenshots/chatcode.png",
    logo: "/logo/chatcode.png",
    categories: ["coding"],
    subcategory: "chatbot",
    tags: ["AI", "chatbot", "developer support"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
  {
    name: "PyCaret",
    description: "AutoML platform for machine learning and coding pipelines.",
    url: "https://pycaret.org",
    id: "pycaret",
    image: "/tool-screenshots/pycaret.png",
    logo: "/logo/pycaret.png",
    categories: ["coding", "data"],
    subcategory: "automl",
    tags: ["AI", "AutoML", "Python"],
    rating: 4.5,
    visits: 1200000,
    dateAdded: "2022-12-01",
    isPremium: 'Free'
  },
  {
    name: "DataRobot Code",
    description: "AI platform for code optimization and deployment.",
    url: "https://www.datarobot.com",
    id: "datarobot-code",
    image: "/tool-screenshots/datarobot-code.png",
    logo: "/logo/datarobot-code.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "deployment", "automation"],
    rating: 4.4,
    visits: 900000,
    dateAdded: "2023-01-01",
    isPremium: 'Free'
  },
  {
    name: "CodeGen",
    description: "Transformer models for code synthesis and generation.",
    url: "https://github.com/salesforce/CodeGen",
    id: "codegen",
    image: "/tool-screenshots/codegen.png",
    logo: "/logo/codegen.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "deep learning", "models"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2023-02-01",
    isPremium: 'Free'
  },
  {
    name: "Sourcery",
    description: "AI-powered Python refactoring and code improvement tool.",
    url: "https://sourcery.ai",
    id: "sourcery",
    image: "/tool-screenshots/sourcery.png",
    logo: "/logo/sourcery.png",
    categories: ["coding"],
    subcategory: "refactoring",
    tags: ["AI", "Python", "refactoring"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2023-03-01",
    isPremium: 'Free'
  },
  {
    name: "Kogito",
    description: "Enterprise automation platform with AI capabilities.",
    url: "https://kogito.kie.org",
    id: "kogito",
    image: "/tool-screenshots/kogito.png",
    logo: "/logo/kogito.png",
    categories: ["coding"],
    subcategory: "automation",
    tags: ["AI", "automation", "business"],
    rating: 4.1,
    visits: 300000,
    dateAdded: "2023-04-01",
    isPremium: 'Free'
  },
  {
    name: "Jina AI",
    description: "Neural search and multimedia pipelines platform.",
    url: "https://jina.ai",
    id: "jina-ai",
    image: "/tool-screenshots/jina-ai.png",
    logo: "/logo/jina-ai.png",
    categories: ["coding", "data"],
    subcategory: "neural-search",
    tags: ["AI", "search", "neural network"],
    rating: 4.4,
    visits: 500000,
    dateAdded: "2023-05-01",
    isPremium: 'Free'
  },
  {
    name: "DeepTabNine",
    description: "GPT-3 based code autocompletion tool.",
    url: "https://www.tabnine.com",
    id: "deeptabnine",
    image: "/tool-screenshots/deeptabnine.png",
    logo: "/logo/deeptabnine.png",
    categories: ["coding"],
    subcategory: "code-autocompletion",
    tags: ["AI", "GPT-3", "IDE"],
    rating: 4.2,
    visits: 400000,
    dateAdded: "2023-06-01",
    isPremium: 'Free'
  },
  {
    name: "Yellowbrick",
    description: "ML model visualization tool for code debugging.",
    url: "https://www.scikit-yb.org",
    id: "yellowbrick",
    image: "/tool-screenshots/yellowbrick.png",
    logo: "/logo/yellowbrick.png",
    categories: ["coding", "data"],
    subcategory: "visualization",
    tags: ["AI", "visualization", "ML"],
    rating: 4.0,
    visits: 200000,
    dateAdded: "2023-07-01",
    isPremium: 'Free'
  },
  {
    name: "OpenAI Codex API",
    description: "API for code generation and assistance.",
    url: "https://openai.com/api",
    id: "openai-codex-api",
    image: "/tool-screenshots/openai-codex-api.png",
    logo: "/logo/openai-codex-api.png",
    categories: ["coding"],
    subcategory: "api",
    tags: ["AI", "API", "GPT-3"],
    rating: 4.6,
    visits: 2500000,
    dateAdded: "2023-08-01",
    isPremium: 'Free'
  },
  {
    name: "Semantic Kernel (Microsoft)",
    description: "AI SDK for automation and code integration.",
    url: "https://github.com/microsoft/semantic-kernel",
    id: "semantic-kernel",
    image: "/tool-screenshots/semantic-kernel.png",
    logo: "/logo/semantic-kernel.png",
    categories: ["coding"],
    subcategory: "sdk",
    tags: ["AI", "SDK", "automation"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2023-09-01",
    isPremium: 'Free'
  },
  {
    name: "ML.NET",
    description: "Machine learning framework for C# and .NET developers.",
    url: "https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet",
    id: "ml-net",
    image: "/tool-screenshots/ml-net.png",
    logo: "/logo/ml-net.png",
    categories: ["coding", "data"],
    subcategory: "ml-framework",
    tags: ["AI", ".NET", "ML"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2023-10-01",
    isPremium: 'Free'
  },
  {
    name: "Hugging Face Transformers",
    description: "Library of pre-trained models for code and NLP tasks.",
    url: "https://huggingface.co/docs/transformers",
    id: "huggingface-transformers",
    image: "/tool-screenshots/huggingface-transformers.png",
    logo: "/logo/huggingface-transformers.png",
    categories: ["coding", "data"],
    subcategory: "models",
    tags: ["AI", "transformers", "models"],
    rating: 4.7,
    visits: 3000000,
    dateAdded: "2023-11-01",
    isPremium: 'Free'
  },
  {
    name: "Codota (Tabnine)",
    description: "AI code completions for Java and JVM languages.",
    url: "https://www.tabnine.com",
    id: "codota",
    image: "/tool-screenshots/codota.png",
    logo: "/logo/codota.png",
    categories: ["coding"],
    subcategory: "code-autocompletion",
    tags: ["AI", "Java", "IDE"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2023-12-01",
    isPremium: 'Free'
  },
  {
    name: "Keras Tuner",
    description: "Hyperparameter optimization tool with AI capabilities.",
    url: "https://keras.io/keras_tuner",
    id: "keras-tuner",
    image: "/tool-screenshots/keras-tuner.png",
    logo: "/logo/keras-tuner.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "hyperparameters", "ML"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2024-01-01",
    isPremium: 'Free'
  },
  {
    name: "MLflow",
    description: "ML lifecycle management and deployment platform.",
    url: "https://mlflow.org",
    id: "mlflow",
    image: "/tool-screenshots/mlflow.png",
    logo: "/logo/mlflow.png",
    categories: ["coding", "data"],
    subcategory: "ml-ops",
    tags: ["AI", "lifecycle", "ML Ops"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2024-02-01",
    isPremium: 'Free'
  },
  {
    name: "Google DeepMind AlphaCode",
    description: "AI system for competitive programming and code synthesis.",
    url: "https://deepmind.com/blog/article/Competitive-programming-with-AlphaCode",
    id: "alphacode",
    image: "/tool-screenshots/alphacode.png",
    logo: "/logo/alphacode.png",
    categories: ["coding"],
    subcategory: "code-synthesis",
    tags: ["AI", "synthesis", "deep learning"],
    rating: 4.8,
    visits: 2000000,
    dateAdded: "2024-03-01",
    isPremium: 'Free'
  },
  {
    name: "ExaCode",
    description: "AI performance tuning and bug detection tool.",
    url: "https://exacode.ai",
    id: "exacode",
    image: "/tool-screenshots/exacode.png",
    logo: "/logo/exacode.png",
    categories: ["coding"],
    subcategory: "performance",
    tags: ["AI", "performance", "bug-finding"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2024-04-01",
    isPremium: 'Free'
  },
  {
    name: "CodeComplete",
    description: "AI-driven code snippets and blocks library.",
    url: "https://codecomplete.ai",
    id: "codecomplete",
    image: "/tool-screenshots/codecomplete.png",
    logo: "/logo/codecomplete.png",
    categories: ["coding"],
    subcategory: "code-snippets",
    tags: ["AI", "snippets", "library"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2024-05-01",
    isPremium: 'Free'
  },
  {
    name: "Debuild.co",
    description: "AI web app builder that generates code from prompts.",
    url: "https://debuild.co",
    id: "debuild",
    image: "/tool-screenshots/debuild.png",
    logo: "/logo/debuild.png",
    categories: ["coding"],
    subcategory: "web-development",
    tags: ["AI", "web development", "no-code"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2024-06-01",
    isPremium: 'Free'
  },
  {
    name: "Chai ML",
    description: "AI assistant for coding suggestions and Q&A.",
    url: "https://chai.ml",
    id: "chai-ml",
    image: "/tool-screenshots/chai-ml.png",
    logo: "/logo/chai-ml.png",
    categories: ["coding"],
    subcategory: "chat-assistant",
    tags: ["AI", "chat", "suggestions"],
    rating: 4.1,
    visits: 300000,
    dateAdded: "2024-07-01",
    isPremium: 'Free'
  },
  {
    name: "DeepAI Code Support",
    description: "AI-based code assistance and error fixing tool.",
    url: "https://deepai.org",
    id: "deepai-code-support",
    image: "/tool-screenshots/deepai-code-support.png",
    logo: "/logo/deepai-code-support.png",
    categories: ["coding"],
    subcategory: "code-assistance",
    tags: ["AI", "bug fixing"],
    rating: 4.0,
    visits: 200000,
    dateAdded: "2024-08-01",
    isPremium: 'Free'
  },
  {
    name: "AI Developer Extensions",
    description: "Collection of IDE plugins for AI coding assistance.",
    url: "https://marketplace.visualstudio.com",
    id: "ai-developer-extensions",
    image: "/tool-screenshots/ai-developer-extensions.png",
    logo: "/logo/ai-developer-extensions.png",
    categories: ["coding"],
    subcategory: "ide-plugins",
    tags: ["AI", "IDE", "plugins"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2024-10-01",
    isPremium: 'Free'
  },
  {
    name: "OpenAI Codex Editor",
    description: "Advanced code editing tools powered by GPT.",
    url: "https://openai.com/blog/openai-codex",
    id: "openai-codex-editor",
    image: "/tool-screenshots/openai-codex-editor.png",
    logo: "/logo/openai-codex-editor.png",
    categories: ["coding"],
    subcategory: "code-editing",
    tags: ["AI", "GPT", "coding tools"],
    rating: 4.6,
    visits: 1800000,
    dateAdded: "2024-11-01",
    isPremium: 'Free'
  },
  {
    name: "Replit AI",
    description: "Integrated AI coding environment for collaborative development.",
    url: "https://replit.com",
    id: "replit-ai",
    image: "/tool-screenshots/replit-ai.png",
    logo: "/logo/replit-ai.png",
    categories: ["coding"],
    subcategory: "ide",
    tags: ["AI", "IDE", "collaborative coding"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2024-12-01",
    isPremium: 'Free'
  },
  {
    name: "CodeSandbox AI",
    description: "AI-assisted code sharing and editing platform.",
    url: "https://codesandbox.io",
    id: "codesandbox-ai",
    image: "/tool-screenshots/codesandbox-ai.png",
    logo: "/logo/codesandbox-ai.png",
    categories: ["coding"],
    subcategory: "web-ide",
    tags: ["AI", "web", "IDE"],
    rating: 4.3,
    visits: 900000,
    dateAdded: "2025-01-01",
    isPremium: 'Free'
  },
  {
    name: "AI CodeReviewer",
    description: "AI-based code review and quality analysis tool.",
    url: "https://aicodereviewer.com",
    id: "ai-codereviewer",
    image: "/tool-screenshots/ai-codereviewer.png",
    logo: "/logo/ai-codereviewer.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "QA"],
    rating: 4.2,
    visits: 700000,
    dateAdded: "2025-02-01",
    isPremium: 'Free'
  },
  {
    name: "GitHub Copilot Labs",
    description: "Experimental tools for AI-assisted coding and learning.",
    url: "https://github.com/features/copilot",
    id: "github-copilot-labs",
    image: "/tool-screenshots/github-copilot-labs.png",
    logo: "/logo/github-copilot-labs.png",
    categories: ["coding"],
    subcategory: "experimental",
    tags: ["AI", "experiment", "IDE"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2025-03-01",
    isPremium: 'Free'
  },
  {
    name: "OpenAI API for Code",
    description: "General purpose API for custom AI code solutions.",
    url: "https://openai.com/api",
    id: "openai-api-code",
    image: "/tool-screenshots/openai-api-code.png",
    logo: "/logo/openai-api-code.png",
    categories: ["coding"],
    subcategory: "api",
    tags: ["AI", "API", "development"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2025-04-01",
    isPremium: 'Free'
  },
  {
    name: "CodeSquire",
    description: "AI-powered technical documentation and code generation tool.",
    url: "https://codesquire.com",
    id: "codesquire",
    image: "/tool-screenshots/codesquire.png",
    logo: "/logo/codesquire.png",
    categories: ["coding"],
    subcategory: "documentation",
    tags: ["AI", "documentation", "developer tools"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2025-05-01",
    isPremium: 'Free'
  },
  {
    name: "bayesianCode",
    description: "Probabilistic programming with AI optimization.",
    url: "https://bayesiancode.com",
    id: "bayesiancode",
    image: "/tool-screenshots/bayesiancode.png",
    logo: "/logo/bayesiancode.png",
    categories: ["coding", "data"],
    subcategory: "probabilistic",
    tags: ["AI", "probabilistic", "optimization"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2025-06-01",
    isPremium: 'Free'
  },
  {
    name: "GPT-4 Programming Assistants",
    description: "Advanced language models for coding tasks.",
    url: "https://openai.com/gpt-4",
    id: "gpt-4-programming",
    image: "/tool-screenshots/gpt-4-programming.png",
    logo: "/logo/gpt-4-programming.png",
    categories: ["coding"],
    subcategory: "programming-assistant",
    tags: ["AI", "GPT-4", "programming"],
    rating: 4.8,
    visits: 3000000,
    dateAdded: "2025-07-01",
    isPremium: 'Free'
  },
  {
    name: "ChatGPT for Developers",
    description: "In-app coding help and interactive assistance.",
    url: "https://chat.openai.com",
    id: "chatgpt-developers",
    image: "/tool-screenshots/chatgpt-developers.png",
    logo: "/logo/chatgpt-developers.png",
    categories: ["coding"],
    subcategory: "chat-assistant",
    tags: ["AI", "chat", "developer tools"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2025-08-01",
    isPremium: 'Free'
  },
  {
    name: "Program Synthesis Tools",
    description: "AI for automatic code generation from specifications.",
    url: "https://program-synthesis.org",
    id: "program-synthesis",
    image: "/tool-screenshots/program-synthesis.png",
    logo: "/logo/program-synthesis.png",
    categories: ["coding"],
    subcategory: "code-synthesis",
    tags: ["AI", "synthesis", "automation"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2025-09-01",
    isPremium: 'Free'
  },
  {
    name: "Cursor",
    description: "AI-powered code completion and suggestions for developers.",
    url: "https://cursor.sh",
    id: "cursor",
    image: "/tool-screenshots/cursor.png",
    logo: "/logo/cursor.png",
    categories: ["coding"],
    subcategory: "code-completion",
    tags: ["AI", "completion", "IDE"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2025-10-01",
    isPremium: 'Free'
  },
  {
    name: "ElevenLabs",
    description: "AI voice synthesis and cloning platform that creates natural-sounding speech from text.",
    url: "https://elevenlabs.io",
    id: "elevenlabs",
    image: "/tool-screenshots/elevenlabs.png",
    logo: "/logo/elevenlabs.png",
    categories: ["audio"],
    subcategory: "voice-synthesis",
    tags: ["AI", "voice", "speech synthesis"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2022-01-15",
    isPremium: 'Free'
  },
  {
    name: "Descript",
    description: "AI-powered audio and video editing platform with text-based editing capabilities.",
    url: "https://www.descript.com",
    id: "descript",
    image: "/tool-screenshots/descript.png",
    logo: "/logo/descript.png",
    categories: ["audio", "video"],
    subcategory: "media-editing",
    tags: ["AI", "audio", "video", "editing"],
    rating: 4.5,
    visits: 1800000,
    dateAdded: "2017-08-01",
    isPremium: 'Free'
  },
  {
    name: "Figma AI",
    description: "AI-powered design tool that helps create and prototype user interfaces with advanced automation features.",
    url: "https://www.figma.com",
    id: "figma-ai",
    image: "/tool-screenshots/figma-ai.png",
    logo: "/logo/figma-ai.png",
    categories: ["design"],
    subcategory: "ui-design",
    tags: ["AI", "UI", "UX", "prototyping"],
    rating: 4.8,
    visits: 5000000,
    dateAdded: "2023-06-15",
    isPremium: 'Free'
  },
  {
    name: "Sketch AI",
    description: "AI-assisted vector graphic design tool for professional designers.",
    url: "https://www.sketch.com",
    id: "sketch-ai",
    image: "/tool-screenshots/sketch-ai.png",
    logo: "/logo/sketch-ai.png",
    categories: ["design"],
    subcategory: "vector-design",
    tags: ["AI", "vector", "design"],
    rating: 4.6,
    visits: 3000000,
    dateAdded: "2023-03-01",
    isPremium: 'Free'
  },
  {
    name: "InVision AI",
    description: "AI-driven prototyping and collaboration platform for design teams.",
    url: "https://www.invisionapp.com",
    id: "invision-ai",
    image: "/tool-screenshots/invision-ai.png",
    logo: "/logo/invision-ai.png",
    categories: ["design"],
    subcategory: "prototyping",
    tags: ["AI", "prototyping", "collaboration"],
    rating: 4.5,
    visits: 2500000,
    dateAdded: "2023-01-15",
    isPremium: 'Free'
  },
  {
    name: "Uizard",
    description: "AI-assisted wireframing and app design platform for rapid prototyping.",
    url: "https://uizard.io",
    id: "uizard",
    image: "/tool-screenshots/uizard.png",
    logo: "/logo/uizard.png",
    categories: ["design"],
    subcategory: "wireframing",
    tags: ["AI", "wireframing", "app design"],
    rating: 4.4,
    visits: 2000000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
  {
    name: "Visily",
    description: "AI-driven UI creation and prototyping tool for modern applications.",
    url: "https://www.visily.ai",
    id: "visily",
    image: "/tool-screenshots/visily.png",
    logo: "/logo/visily.png",
    categories: ["design"],
    subcategory: "ui-creation",
    tags: ["AI", "UI", "prototyping"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2022-09-15",
    isPremium: 'Free'
  },
  {
    name: "AutoDraw",
    description: "AI-powered tool that transforms quick sketches into professional drawings.",
    url: "https://www.autodraw.com",
    id: "autodraw",
    image: "/tool-screenshots/autodraw.png",
    logo: "/logo/autodraw.png",
    categories: ["design"],
    subcategory: "sketching",
    tags: ["AI", "sketching", "drawing"],
    rating: 4.2,
    visits: 1200000,
    dateAdded: "2022-07-01",
    isPremium: 'Free'
  },
  {
    name: "Beautiful.ai",
    description: "AI-powered presentation design platform for creating stunning slides.",
    url: "https://www.beautiful.ai",
    id: "beautiful-ai",
    image: "/tool-screenshots/beautiful-ai.png",
    logo: "/logo/beautiful-ai.png",
    categories: ["design"],
    subcategory: "presentation",
    tags: ["AI", "presentation", "slides"],
    rating: 4.5,
    visits: 1800000,
    dateAdded: "2022-05-15",
    isPremium: 'Free'
  },
  {
    name: "Lunacy",
    description: "AI-based UI design tool compatible with Sketch for professional designers.",
    url: "https://icons8.com/lunacy",
    id: "lunacy",
    image: "/tool-screenshots/lunacy.png",
    logo: "/logo/lunacy.png",
    categories: ["design"],
    subcategory: "ui-design",
    tags: ["AI", "UI design", "compatibility"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
  {
    name: "Looka",
    description: "AI-powered logo and branding platform for businesses.",
    url: "https://looka.com",
    id: "looka",
    image: "/tool-screenshots/looka.png",
    logo: "/logo/looka.png",
    categories: ["design"],
    subcategory: "branding",
    tags: ["AI", "branding", "logo design"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2022-01-15",
    isPremium: 'Free'
  },
  {
    name: "Khroma",
    description: "AI-driven color palette generator for designers and artists.",
    url: "https://www.khroma.co",
    id: "khroma",
    image: "/tool-screenshots/khroma.png",
    logo: "/logo/khroma.png",
    categories: ["design"],
    subcategory: "color-tools",
    tags: ["AI", "colors", "palette"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2021-11-01",
    isPremium: 'Free'
  },
  {
    name: "Designs.ai",
    description: "Comprehensive AI tools for branding, videos, and graphics creation.",
    url: "https://designs.ai",
    id: "designs-ai",
    image: "/tool-screenshots/designs-ai.png",
    logo: "/logo/designs-ai.png",
    categories: ["design"],
    subcategory: "branding",
    tags: ["AI", "branding", "video", "graphics"],
    rating: 4.4,
    visits: 900000,
    dateAdded: "2021-09-15",
    isPremium: 'Free'
  },
  {
    name: "Tailor Brands",
    description: "AI-powered comprehensive branding and logo design platform.",
    url: "https://www.tailorbrands.com",
    id: "tailor-brands",
    image: "/tool-screenshots/tailor-brands.png",
    logo: "/logo/tailor-brands.png",
    categories: ["design"],
    subcategory: "branding",
    tags: ["AI", "branding", "logo"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2021-07-01",
    isPremium: 'Free'
  },
  {
    name: "Designify",
    description: "AI-powered product and fashion image enhancement platform.",
    url: "https://designify.com",
    id: "designify",
    image: "/tool-screenshots/designify.png",
    logo: "/logo/designify.png",
    categories: ["design"],
    subcategory: "image-enhancement",
    tags: ["AI", "product", "fashion", "image editing"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2021-05-15",
    isPremium: 'Free'
  },
  {
    name: "Vidnami (formerly Content Samurai)",
    description: "AI video ads & marketing videos platform.",
    url: "https://www.vidnami.com",
    id: "vidnami",
    image: "/tool-screenshots/vidnami.png",
    logo: "/logo/vidnami.png",
    categories: ["marketing"],
    subcategory: "video-ads",
    tags: ["AI", "video", "advertising"],
    rating: 4.3,
    visits: 200000,
    dateAdded: "2022-04-15",
    isPremium: 'Free',
  },
  {
    name: "Designs.ai Videomaker",
    description: "Branded & marketing videos with AI platform.",
    url: "https://designs.ai/videomaker",
    id: "designs-ai-videomaker",
    image: "/tool-screenshots/designs-ai-videomaker.png",
    logo: "/logo/designs-ai-videomaker.png",
    categories: ["marketing"],
    subcategory: "video-creation",
    tags: ["AI", "video", "branding"],
    rating: 4.4,
    visits: 180000,
    dateAdded: "2022-05-15",
    isPremium: 'Free',
  },
  {
    name: "Pattern89",
    description: "AI ad optimization & performance analytics platform.",
    url: "https://pattern89.com",
    id: "pattern89",
    image: "/tool-screenshots/pattern89.png",
    logo: "/logo/pattern89.png",
    categories: ["marketing"],
    subcategory: "ad-optimization",
    tags: ["AI", "advertising", "analytics"],
    rating: 4.5,
    visits: 150000,
    dateAdded: "2022-06-15",
    isPremium: 'Free',
  },
  {
    name: "Adext AI",
    description: "AI-automated ad management & optimization platform.",
    url: "https://adext.com",
    id: "adext-ai",
    image: "/tool-screenshots/adext-ai.png",
    logo: "/logo/adext-ai.png",
    categories: ["marketing"],
    subcategory: "ad-management",
    tags: ["AI", "ads", "automation"],
    rating: 4.3,
    visits: 120000,
    dateAdded: "2022-07-15",
    isPremium: 'Free',
  },
  {
    name: "Albert.ai",
    description: "Autonomous AI marketing & ad campaign management platform.",
    url: "https://albert.ai",
    id: "albert-ai",
    image: "/tool-screenshots/albert-ai.png",
    logo: "/logo/albert-ai.png",
    categories: ["marketing"],
    subcategory: "campaign-management",
    tags: ["AI", "campaign", "automation"],
    rating: 4.6,
    visits: 100000,
    dateAdded: "2022-08-15",
    isPremium: 'Free',
  },
  {
    name: "Crimson Hexagon (now part of Brandwatch)",
    description: "AI sentiment & market analysis platform.",
    url: "https://www.brandwatch.com",
    id: "crimson-hexagon",
    image: "/tool-screenshots/crimson-hexagon.png",
    logo: "/logo/crimson-hexagon.png",
    categories: ["marketing"],
    subcategory: "market-analysis",
    tags: ["AI", "sentiment", "market research"],
    rating: 4.4,
    visits: 90000,
    dateAdded: "2022-09-15",
    isPremium: 'Free',
  },
  {
    name: "NetBase Quid",
    description: "AI social media & consumer insights platform.",
    url: "https://www.quid.com",
    id: "netbase-quid",
    image: "/tool-screenshots/netbase-quid.png",
    logo: "/logo/netbase-quid.png",
    categories: ["marketing"],
    subcategory: "social-insights",
    tags: ["AI", "social media", "insights"],
    rating: 4.5,
    visits: 80000,
    dateAdded: "2022-10-15",
    isPremium: 'Free',
  },
  {
    name: "Sprout Social",
    description: "Social media management with AI insights platform.",
    url: "https://sproutsocial.com",
    id: "sprout-social",
    image: "/tool-screenshots/sprout-social.png",
    logo: "/logo/sprout-social.png",
    categories: ["marketing"],
    subcategory: "social-management",
    tags: ["AI", "social media", "management"],
    rating: 4.6,
    visits: 70000,
    dateAdded: "2022-11-15",
    isPremium: 'Free',
  },
  {
    name: "Hootsuite Insights",
    description: "AI-powered social analytics platform.",
    url: "https://hootsuite.com/products/insights",
    id: "hootsuite-insights",
    image: "/tool-screenshots/hootsuite-insights.png",
    logo: "/logo/hootsuite-insights.png",
    categories: ["marketing"],
    subcategory: "social-analytics",
    tags: ["AI", "social media", "analytics"],
    rating: 4.3,
    visits: 60000,
    dateAdded: "2022-12-15",
    isPremium: 'Free',
  },
  {
    name: "Crayon",
    description: "Competitive intelligence with AI insights platform.",
    url: "https://www.crayon.co",
    id: "crayon",
    image: "/tool-screenshots/crayon.png",
    logo: "/logo/crayon.png",
    categories: ["marketing"],
    subcategory: "competitive-intelligence",
    tags: ["AI", "competitive analysis"],
    rating: 4.4,
    visits: 50000,
    dateAdded: "2023-01-15",
    isPremium: 'Free',
  },
  {
    name: "Crush Card",
    description: "AI lead scoring & customer segmentation platform.",
    url: "https://crushcard.com",
    id: "crush-card",
    image: "/tool-screenshots/crush-card.png",
    logo: "/logo/crush-card.png",
    categories: ["marketing"],
    subcategory: "lead-scoring",
    tags: ["AI", "lead scoring", "segmentation"],
    rating: 4.2,
    visits: 40000,
    dateAdded: "2023-02-15",
    isPremium: 'Free',
  },
  {
    name: "LeadGenius",
    description: "AI-driven lead generation & data enrichment platform.",
    url: "https://www.leadgenius.com",
    id: "leadgenius",
    image: "/tool-screenshots/leadgenius.png",
    logo: "/logo/leadgenius.png",
    categories: ["marketing"],
    subcategory: "lead-generation",
    tags: ["AI", "lead generation"],
    rating: 4.3,
    visits: 35000,
    dateAdded: "2023-03-15",
    isPremium: 'Free',
  },
  {
    name: "InsideView",
    description: "AI market & customer intelligence platform.",
    url: "https://www.insideview.com",
    id: "insideview",
    image: "/tool-screenshots/insideview.png",
    logo: "/logo/insideview.png",
    categories: ["marketing"],
    subcategory: "market-intelligence",
    tags: ["AI", "market research"],
    rating: 4.4,
    visits: 30000,
    dateAdded: "2023-04-15",
    isPremium: 'Free',
  },
  {
    name: "Marketo (Adobe)",
    description: "Marketing automation with AI features platform.",
    url: "https://www.marketo.com",
    id: "marketo",
    image: "/tool-screenshots/marketo.png",
    logo: "/logo/marketo.png",
    categories: ["marketing"],
    subcategory: "marketing-automation",
    tags: ["AI", "marketing automation"],
    rating: 4.5,
    visits: 25000,
    dateAdded: "2023-05-15",
    isPremium: 'Free',
  },
  {
    name: "HubSpot",
    description: "CRM & marketing with AI prediction & automation platform.",
    url: "https://www.hubspot.com",
    id: "hubspot",
    image: "/tool-screenshots/hubspot.png",
    logo: "/logo/hubspot.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "automation"],
    rating: 4.6,
    visits: 20000,
    dateAdded: "2023-06-15",
    isPremium: 'Free',
  },
  {
    name: "Salesforce Einstein",
    description: "AI-powered CRM & marketing tools platform.",
    url: "https://www.salesforce.com/products/einstein/overview",
    id: "salesforce-einstein",
    image: "/tool-screenshots/salesforce-einstein.png",
    logo: "/logo/salesforce-einstein.png",
    categories: ["marketing"],
    subcategory: "crm",
    tags: ["AI", "CRM", "predictive analytics"],
    rating: 4.7,
    visits: 18000,
    dateAdded: "2023-07-15",
    isPremium: 'Free',
  },
  {
    name: "AlluxiQA",
    description: "AI-driven B2B marketing personalization platform.",
    url: "https://www.alluxiqa.com",
    id: "alluxiqa",
    image: "/tool-screenshots/alluxiqa.png",
    logo: "/logo/alluxiqa.png",
    categories: ["marketing"],
    subcategory: "b2b-marketing",
    tags: ["AI", "personalization", "B2B"],
    rating: 4.3,
    visits: 15000,
    dateAdded: "2023-08-15",
    isPremium: 'Free',
  },
  {
    name: "Persado",
    description: "AI language & message optimization for marketing platform.",
    url: "https://www.persado.com",
    id: "persado",
    image: "/tool-screenshots/persado.png",
    logo: "/logo/persado.png",
    categories: ["marketing"],
    subcategory: "message-optimization",
    tags: ["AI", "messaging", "language"],
    rating: 4.4,
    visits: 12000,
    dateAdded: "2023-09-15",
    isPremium: 'Free',
  },
  {
    name: "Vennli",
    description: "AI-driven strategic marketing & customer insights platform.",
    url: "https://www.vennli.com",
    id: "vennli",
    image: "/tool-screenshots/vennli.png",
    logo: "/logo/vennli.png",
    categories: ["marketing"],
    subcategory: "strategic-marketing",
    tags: ["AI", "strategy", "insights"],
    rating: 4.2,
    visits: 10000,
    dateAdded: "2023-10-15",
    isPremium: 'Free',
  },
  {
    name: "VocalVine",
    description: "AI-based voice & video content marketing platform.",
    url: "https://www.vocalvine.com",
    id: "vocalvine",
    image: "/tool-screenshots/vocalvine.png",
    logo: "/logo/vocalvine.png",
    categories: ["marketing"],
    subcategory: "content-marketing",
    tags: ["AI", "voice", "video marketing"],
    rating: 4.3,
    visits: 8000,
    dateAdded: "2023-11-15",
    isPremium: 'Free',
  },
  {
    name: "Unbounce Smart Traffic",
    description: "AI-powered landing page optimization platform.",
    url: "https://unbounce.com",
    id: "unbounce",
    image: "/tool-screenshots/unbounce.png",
    logo: "/logo/unbounce.png",
    categories: ["marketing"],
    subcategory: "landing-pages",
    tags: ["AI", "landing pages", "CRO"],
    rating: 4.5,
    visits: 6000,
    dateAdded: "2023-12-15",
    isPremium: 'Free',
  },
  {
    name: "Optimizely (formerly Episerver)",
    description: "AI-driven experimentation & personalization platform.",
    url: "https://www.optimizely.com",
    id: "optimizely",
    image: "/tool-screenshots/optimizely.png",
    logo: "/logo/optimizely.png",
    categories: ["marketing"],
    subcategory: "personalization",
    tags: ["AI", "personalization", "experimentation"],
    rating: 4.6,
    visits: 5000,
    dateAdded: "2024-01-15",
    isPremium: 'Free',
  },
  {
    name: "Amplify.ai",
    description: "AI-powered conversational marketing & chatbots platform.",
    url: "https://amplify.ai",
    id: "amplify-ai",
    image: "/tool-screenshots/amplify-ai.png",
    logo: "/logo/amplify-ai.png",
    categories: ["marketing"],
    subcategory: "conversational-marketing",
    tags: ["AI", "chatbots", "conversational marketing"],
    rating: 4.4,
    visits: 4000,
    dateAdded: "2024-02-15",
    isPremium: 'Free',
  },
  {
    name: "Drift",
    description: "AI chatbot & conversational marketing platform.",
    url: "https://www.drift.com",
    id: "drift",
    image: "/tool-screenshots/drift.png",
    logo: "/logo/drift.png",
    categories: ["marketing"],
    subcategory: "conversational-marketing",
    tags: ["AI", "chat", "marketing"],
    rating: 4.5,
    visits: 3000,
    dateAdded: "2024-03-15",
    isPremium: 'Free',
  },
  {
    name: "Intercom",
    description: "AI-powered customer engagement & messaging platform.",
    url: "https://www.intercom.com",
    id: "intercom",
    image: "/tool-screenshots/intercom.png",
    logo: "/logo/intercom.png",
    categories: ["marketing"],
    subcategory: "customer-engagement",
    tags: ["AI", "customer engagement"],
    rating: 4.6,
    visits: 2500,
    dateAdded: "2024-04-15",
    isPremium: 'Free',
  },
  {
    name: "ActiveCampaign",
    description: "Marketing automation & CRM with AI insights platform.",
    url: "https://www.activecampaign.com",
    id: "activecampaign",
    image: "/tool-screenshots/activecampaign.png",
    logo: "/logo/activecampaign.png",
    categories: ["marketing"],
    subcategory: "marketing-automation",
    tags: ["AI", "automation", "CRM"],
    rating: 4.4,
    visits: 2000,
    dateAdded: "2024-05-15",
    isPremium: 'Free',
  },
  {
    name: "Sentient Technologies",
    description: "AI for digital marketing and conversion optimization platform.",
    url: "https://www.sentient.ai",
    id: "sentient-technologies",
    image: "/tool-screenshots/sentient-technologies.png",
    logo: "/logo/sentient-technologies.png",
    categories: ["marketing"],
    subcategory: "conversion-optimization",
    tags: ["AI", "conversion"],
    rating: 4.3,
    visits: 1500,
    dateAdded: "2024-06-15",
    isPremium: 'Free',
  }
] 