import React from 'react'
import {
  Code,
  ImageIcon,
  MessageSquare,
  Mic,
  PenTool,
  Briefcase,
  Brain,
  Video,
  LineChart,
  Database,
  BarChart,
} from "lucide-react"
import type { Tool, Category } from "./types"

// Categories with icons
export const categories: Category[] = [
  {
    name: "Text",
    description: "AI tools for generating text content, including copywriting, content creation, and text completion.",
    icon: <MessageSquare className="h-4 w-4" />,
    id: "text"
  },
  {
    name: "Image",
    description: "Create images, art, and designs using AI-powered tools.",
    icon: <ImageIcon className="h-4 w-4" />,
    id: "image"
  },
  {
    name: "Coding",
    description: "AI assistants and tools to help with programming, code generation, and debugging.",
    icon: <Code className="h-4 w-4" />,
    id: "coding"
  },
  {
    name: "Audio",
    description: "Tools for voice synthesis, transcription, and audio processing.",
    icon: <Mic className="h-4 w-4" />,
    id: "audio"
  },
  {
    name: "Design",
    description: "AI-powered design tools for UI/UX, graphic design, and creative work.",
    icon: <PenTool className="h-4 w-4" />,
    id: "design"
  },
  {
    name: "Productivity",
    description: "Tools to enhance workflow, automate tasks, and improve efficiency.",
    icon: <Briefcase className="h-4 w-4" />,
    id: "productivity"
  },
  {
    name: "Research",
    description: "AI tools for data analysis, research assistance, and knowledge discovery.",
    icon: <Brain className="h-4 w-4" />,
    id: "research"
  },
  {
    name: "Video",
    description: "Tools for video generation, editing, and enhancement using AI.",
    icon: <Video className="h-4 w-4" />,
    id: "video"
  },
  {
    name: "Analytics",
    description: "AI-powered analytics tools for data insights and business intelligence.",
    icon: <LineChart className="h-4 w-4" />,
    id: "analytics"
  },
  {
    name: "Data Processing",
    description: "Tools for data extraction, transformation, and processing with AI.",
    icon: <Database className="h-4 w-4" />,
    id: "data-processing"
  },
  {
    name: "Marketing",
    description: "AI-powered tools for content creation, marketing automation, and campaign optimization.",
    icon: <BarChart className="h-4 w-4" />,
    id: "marketing"
  }
]

// Combined tools data
export const tools: Tool[] = [
  {
    name: "Jasper (formerly Jarvis)",
    description: "AI content creation & copywriting platform.",
    url: "https://www.jasper.ai",
    id: "jasper",
    image: "/tool-screenshots/jasper.png",
    logo: "/logo/jasper.png",
    categories: ["marketing"],
    subcategory: "content-creation",
    tags: ["AI", "content", "copywriting"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2021-01-15",
    isPremium: 'Free'
  },
  {
    name: "Conversion.ai (Jasper AI)",
    description: "AI marketing & sales copy generation platform.",
    url: "https://www.conversion.ai",
    id: "conversion-ai",
    image: "/tool-screenshots/conversion-ai.png",
    logo: "/logo/conversion-ai.png",
    categories: ["marketing"],
    subcategory: "sales-copy",
    tags: ["AI", "marketing", "sales"],
    rating: 4.6,
    visits: 600000,
    dateAdded: "2021-10-15",
    isPremium: 'Free'
  },
  {
    name: "CopySmith",
    description: "AI content generation for marketing platform.",
    url: "https://copysmith.ai",
    id: "copysmith",
    image: "/tool-screenshots/copysmith.png",
    logo: "/logo/copysmith.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.3,
    visits: 400000,
    dateAdded: "2021-12-15",
    isPremium: 'Free'
  },
  {
    name: "Copyscape",
    description: "AI-powered plagiarism detection & content validation platform.",
    url: "https://www.copyscape.com",
    id: "copyscape",
    image: "/tool-screenshots/copyscape.png",
    logo: "/logo/copyscape.png",
    categories: ["marketing"],
    subcategory: "content-validation",
    tags: ["AI", "plagiarism", "content"],
    rating: 4.4,
    visits: 350000,
    dateAdded: "2022-01-15",
    isPremium: 'Free'
  },
  {
    name: "Grammarly",
    description: "AI-powered writing assistant that helps you write better by checking grammar, spelling, and style.",
    url: "https://www.grammarly.com",
    id: "grammarly",
    image: "/tool-screenshots/grammarly.png",
    logo: "/logo/grammarly.png",
    categories: ["text", "productivity"],
    subcategory: "grammar",
    tags: ["AI", "grammar", "proofreading", "editing"],
    rating: 4.7,
    visits: 12000000,
    dateAdded: "2020-09-15",
    isPremium: 'Free'
  },
  {
    name: "QuillBot",
    description: "AI-powered paraphrasing tool that helps you rewrite and improve your text while maintaining its meaning.",
    url: "https://quillbot.com",
    id: "quillbot",
    image: "/tool-screenshots/quillbot.png",
    logo: "/logo/quillbot.png",
    categories: ["text", "productivity"],
    subcategory: "paraphrasing",
    tags: ["AI", "paraphrasing", "rewriting", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2021-03-20",
    isPremium: 'Free'
  },
  {
    name: "ProWritingAid",
    description: "Comprehensive writing tool that helps you improve your writing style, grammar, and readability.",
    url: "https://prowritingaid.com",
    id: "prowritingaid",
    image: "/tool-screenshots/prowritingaid.png",
    logo: "/logo/prowritingaid.png",
    categories: ["text", "productivity"],
    subcategory: "style-editing",
    tags: ["AI", "style", "editing", "readability"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-06-15",
    isPremium: 'Free'
  },
  {
    name: "Hemingway App",
    description: "AI-powered writing tool that helps you write clear, concise, and readable content.",
    url: "https://hemingwayapp.com",
    id: "hemingway-app",
    image: "/tool-screenshots/hemingway-app.png",
    logo: "/logo/hemingway-app.png",
    categories: ["text", "productivity"],
    subcategory: "readability",
    tags: ["AI", "readability", "writing", "style"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-20",
    isPremium: 'Free'
  },
  {
    name: "Synthesia",
    description: "AI video creators for marketing platform.",
    url: "https://www.synthesia.io",
    id: "synthesia",
    image: "/tool-screenshots/synthesia.png",
    logo: "/logo/synthesia.png",
    categories: ["marketing"],
    subcategory: "video-creation",
    tags: ["AI", "video", "marketing"],
    rating: 4.6,
    visits: 250000,
    dateAdded: "2022-03-15",
    isPremium: 'Free'
  },
  {
    name: "Lumen5",
    description: "AI social media video content creation platform.",
    url: "https://lumen5.com",
    id: "lumen5",
    image: "/tool-screenshots/lumen5.png",
    logo: "/logo/lumen5.png",
    categories: ["marketing"],
    subcategory: "video-content",
    tags: ["AI", "video", "social media"],
    rating: 4.5,
    visits: 300000,
    dateAdded: "2022-02-15",
    isPremium: 'Free'
  },
  {
    name: "Mem",
    description: "AI-powered note organization and intelligent retrieval platform.",
    url: "https://mem.ai",
    id: "mem",
    image: "/tool-screenshots/mem.png",
    logo: "/logo/mem.png",
    categories: ["productivity"],
    subcategory: "note-organization",
    tags: ["AI", "notes", "organization"],
    rating: 4.1,
    visits: 3000,
    dateAdded: "2026-11-15",
    isPremium: 'Free'
  },
  {
    name: "Hugo AI",
    description: "Knowledge management and AI writing assistant.",
    url: "https://hugo.ai",
    id: "hugo-ai",
    image: "/tool-screenshots/hugo-ai.png",
    logo: "/logo/hugo-ai.png",
    categories: ["productivity"],
    subcategory: "knowledge-management",
    tags: ["AI", "knowledge", "writing"],
    rating: 4.3,
    visits: 6000,
    dateAdded: "2026-07-15",
    isPremium: 'Free'
  },
  {
    name: "AI Dungeon",
    description: "Storytelling and creative writing AI for entertainment and inspiration.",
    url: "https://aidungeon.io",
    id: "ai-dungeon",
    image: "/tool-screenshots/ai-dungeon.png",
    logo: "/logo/ai-dungeon.png",
    categories: ["productivity"],
    subcategory: "creative-writing",
    tags: ["AI", "storytelling", "creativity"],
    rating: 4.0,
    visits: 10000,
    dateAdded: "2026-03-15",
    isPremium: 'Free'
  },
  {
    name: "Stable Diffusion",
    description: "Open-source AI model for generating high-quality images from text descriptions.",
    url: "https://stability.ai",
    id: "stable-diffusion",
    image: "/tool-screenshots/stable-diffusion.png",
    logo: "/logo/stable-diffusion.png",
    categories: ["image"],
    subcategory: "open-source",
    tags: ["AI", "open-source", "art", "creative"],
    rating: 4.5,
    visits: 6000000,
    dateAdded: "2022-08-22",
    isPremium: 'Free'
  },
  {
    name: "Adobe Firefly",
    description: "Adobe's AI-powered tool for creating creative assets and image design.",
    url: "https://firefly.adobe.com",
    id: "adobe-firefly",
    image: "/tool-screenshots/adobe-firefly.png",
    logo: "/logo/adobe-firefly.png",
    categories: ["image", "design"],
    subcategory: "creative-assets",
    tags: ["AI", "Adobe", "graphic design"],
    rating: 4.7,
    visits: 5000000,
    dateAdded: "2023-03-21",
    isPremium: 'Free'
  },
  {
    name: "Canva AI",
    description: "AI-powered graphic design platform for creating professional images and templates.",
    url: "https://canva.com",
    id: "canva-ai",
    image: "/tool-screenshots/canva-ai.png",
    logo: "/logo/canva-ai.png",
    categories: ["image", "design"],
    subcategory: "graphic-design",
    tags: ["AI", "design", "graphics", "templates"],
    rating: 4.6,
    visits: 8000000,
    dateAdded: "2023-01-15",
    isPremium: 'Free'
  },
  {
    name: "Artbreeder",
    description: "AI platform for genetic image merging and creative image generation.",
    url: "https://artbreeder.com",
    id: "artbreeder",
    image: "/tool-screenshots/artbreeder.png",
    logo: "/logo/artbreeder.png",
    categories: ["image"],
    subcategory: "image-blending",
    tags: ["AI", "image blending", "art"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-08-01",
    isPremium: 'Free'
  },
  {
    name: "Lensa AI",
    description: "AI-powered portrait and photo editing app.",
    url: "https://lensa-ai.com",
    id: "lensa-ai",
    image: "/tool-screenshots/lensa-ai.png",
    logo: "/logo/lensa-ai.png",
    categories: ["image"],
    subcategory: "portrait",
    tags: ["AI", "portrait", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
  {
    name: "StarryAI",
    description: "AI platform for generating art and NFTs.",
    url: "https://starryai.com",
    id: "starryai",
    image: "/tool-screenshots/starryai.png",
    logo: "/logo/starryai.png",
    categories: ["image"],
    subcategory: "nft-art",
    tags: ["AI", "art", "NFTs", "creativity"],
    rating: 4.4,
    visits: 2000000,
    dateAdded: "2022-06-01",
    isPremium: 'Free'
  },
  {
    name: "Jasper Art",
    description: "AI tool for generating content marketing images.",
    url: "https://jasper.ai/art",
    id: "jasper-art",
    image: "/tool-screenshots/jasper-art.png",
    logo: "/logo/jasper-art.png",
    categories: ["image", "marketing"],
    subcategory: "marketing",
    tags: ["AI", "marketing", "content", "art"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2022-04-01",
    isPremium: 'Free'
  },
  {
    name: "Craiyon (formerly DALL·E Mini)",
    description: "Quick and accessible text-to-image generation tool.",
    url: "https://craiyon.com",
    id: "craiyon",
    image: "/tool-screenshots/craiyon.png",
    logo: "/logo/craiyon.png",
    categories: ["image"],
    subcategory: "quick-generation",
    tags: ["AI", "art", "quick generation"],
    rating: 4.1,
    visits: 3000000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
  {
    name: "Deep Nostalgia",
    description: "AI tool for animating photos from still images.",
    url: "https://myheritage.com/deep-nostalgia",
    id: "deep-nostalgia",
    image: "/tool-screenshots/deep-nostalgia.png",
    logo: "/logo/deep-nostalgia.png",
    categories: ["image", "video"],
    subcategory: "animation",
    tags: ["AI", "animation", "photo"],
    rating: 4.3,
    visits: 2500000,
    dateAdded: "2022-01-01",
    isPremium: 'Free'
  },
  {
    name: "FaceApp",
    description: "AI-powered app for facial transformations and edits.",
    url: "https://faceapp.com",
    id: "faceapp",
    image: "/tool-screenshots/faceapp.png",
    logo: "/logo/faceapp.png",
    categories: ["image"],
    subcategory: "face-editing",
    tags: ["AI", "faces", "editing"],
    rating: 4.4,
    visits: 3500000,
    dateAdded: "2021-12-01",
    isPremium: 'Free'
  },
  {
    name: "Amazon CodeWhisperer",
    description: "AI-powered code generation tool integrated with AWS services.",
    url: "https://aws.amazon.com/codewhisperer",
    id: "amazon-codewhisperer",
    image: "/tool-screenshots/amazon-codewhisperer.png",
    logo: "/logo/amazon-codewhisperer.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "code", "automation", "AWS"],
    rating: 4.5,
    visits: 3000000,
    dateAdded: "2022-06-23",
    isPremium: 'Free'
  },
  {
    name: "Replit Ghostwriter",
    description: "AI coding assistant integrated directly into the Replit IDE for seamless development.",
    url: "https://replit.com/ghostwriter",
    id: "replit-ghostwriter",
    image: "/tool-screenshots/replit-ghostwriter.png",
    logo: "/logo/replit-ghostwriter.png",
    categories: ["coding"],
    subcategory: "ide-integration",
    tags: ["AI", "IDE", "code generation", "collaboration"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2023-01-10",
    isPremium: 'Free'
  },
  {
    name: "DeepCode (Snyk Code)",
    description: "AI-driven code review and bug detection platform for improved code quality.",
    url: "https://snyk.io/product/snyk-code",
    id: "deepcode",
    image: "/tool-screenshots/deepcode.png",
    logo: "/logo/deepcode.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "bug fixing"],
    rating: 4.5,
    visits: 1800000,
    dateAdded: "2021-08-20",
    isPremium: 'Free'
  },
  {
    name: "CodeT5",
    description: "Multi-language code understanding and generation model.",
    url: "https://github.com/salesforce/CodeT5",
    id: "codet5",
    image: "/tool-screenshots/codet5.png",
    logo: "/logo/codet5.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "T5", "models"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2022-08-15",
    isPremium: 'Free'
  },
  {
    name: "ChatCode",
    description: "Interactive AI coding chatbot for developer support.",
    url: "https://chatcodeai.vercel.app/",
    id: "chatcode",
    image: "/tool-screenshots/chatcode.png",
    logo: "/logo/chatcode.png",
    categories: ["coding"],
    subcategory: "chatbot",
    tags: ["AI", "chatbot", "developer support"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
  {
    name: "PyCaret",
    description: "AutoML platform for machine learning and coding pipelines.",
    url: "https://pycaret.org",
    id: "pycaret",
    image: "/tool-screenshots/pycaret.png",
    logo: "/logo/pycaret.png",
    categories: ["coding", "data"],
    subcategory: "automl",
    tags: ["AI", "AutoML", "Python"],
    rating: 4.5,
    visits: 1200000,
    dateAdded: "2022-12-01",
    isPremium: 'Free'
  },
  {
    name: "DataRobot Code",
    description: "AI platform for code optimization and deployment.",
    url: "https://www.datarobot.com",
    id: "datarobot-code",
    image: "/tool-screenshots/datarobot-code.png",
    logo: "/logo/datarobot-code.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "deployment", "automation"],
    rating: 4.4,
    visits: 900000,
    dateAdded: "2023-01-01",
    isPremium: 'Free'
  },
  {
    name: "CodeGen",
    description: "Transformer models for code synthesis and generation.",
    url: "https://github.com/salesforce/CodeGen",
    id: "codegen",
    image: "/tool-screenshots/codegen.png",
    logo: "/logo/codegen.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "deep learning", "models"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2023-02-01",
    isPremium: 'Free'
  },
  {
    name: "Sourcery",
    description: "AI-powered Python refactoring and code improvement tool.",
    url: "https://sourcery.ai",
    id: "sourcery",
    image: "/tool-screenshots/sourcery.png",
    logo: "/logo/sourcery.png",
    categories: ["coding"],
    subcategory: "refactoring",
    tags: ["AI", "Python", "refactoring"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2023-03-01",
    isPremium: 'Free'
  },
  {
    name: "Kogito",
    description: "Enterprise automation platform with AI capabilities.",
    url: "https://kogito.kie.org",
    id: "kogito",
    image: "/tool-screenshots/kogito.png",
    logo: "/logo/kogito.png",
    categories: ["coding"],
    subcategory: "automation",
    tags: ["AI", "automation", "business"],
    rating: 4.1,
    visits: 300000,
    dateAdded: "2023-04-01",
    isPremium: 'Free'
  },
  {
    name: "Jina AI",
    description: "Neural search and multimedia pipelines platform.",
    url: "https://jina.ai",
    id: "jina-ai",
    image: "/tool-screenshots/jina-ai.png",
    logo: "/logo/jina-ai.png",
    categories: ["coding", "data"],
    subcategory: "neural-search",
    tags: ["AI", "search", "neural network"],
    rating: 4.4,
    visits: 500000,
    dateAdded: "2023-05-01",
    isPremium: 'Free'
  },
  {
    name: "Yellowbrick",
    description: "ML model visualization tool for code debugging.",
    url: "https://www.scikit-yb.org",
    id: "yellowbrick",
    image: "/tool-screenshots/yellowbrick.png",
    logo: "/logo/yellowbrick.png",
    categories: ["coding", "data"],
    subcategory: "visualization",
    tags: ["AI", "visualization", "ML"],
    rating: 4.0,
    visits: 200000,
    dateAdded: "2023-07-01",
    isPremium: 'Free'
  },
  {
    name: "Semantic Kernel (Microsoft)",
    description: "AI SDK for automation and code integration.",
    url: "https://github.com/microsoft/semantic-kernel",
    id: "semantic-kernel",
    image: "/tool-screenshots/semantic-kernel.png",
    logo: "/logo/semantic-kernel.png",
    categories: ["coding"],
    subcategory: "sdk",
    tags: ["AI", "SDK", "automation"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2023-09-01",
    isPremium: 'Free'
  },
  {
    name: "ML.NET",
    description: "Machine learning framework for C# and .NET developers.",
    url: "https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet",
    id: "ml-net",
    image: "/tool-screenshots/ml-net.png",
    logo: "/logo/ml-net.png",
    categories: ["coding", "data"],
    subcategory: "ml-framework",
    tags: ["AI", ".NET", "ML"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2023-10-01",
    isPremium: 'Free'
  },
  {
    name: "Hugging Face Transformers",
    description: "Library of pre-trained models for code and NLP tasks.",
    url: "https://huggingface.co/docs/transformers",
    id: "huggingface-transformers",
    image: "/tool-screenshots/huggingface-transformers.png",
    logo: "/logo/huggingface-transformers.png",
    categories: ["coding", "data"],
    subcategory: "models",
    tags: ["AI", "transformers", "models"],
    rating: 4.7,
    visits: 3000000,
    dateAdded: "2023-11-01",
    isPremium: 'Free'
  },
  {
    name: "Keras Tuner",
    description: "Hyperparameter optimization tool with AI capabilities.",
    url: "https://keras.io/keras_tuner",
    id: "keras-tuner",
    image: "/tool-screenshots/keras-tuner.png",
    logo: "/logo/keras-tuner.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "hyperparameters", "ML"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2024-01-01",
    isPremium: 'Free'
  },
  {
    name: "ElevenLabs",
    description: "Advanced AI voice cloning and synthesis platform supporting multiple languages and dubbing capabilities.",
    url: "https://elevenlabs.io",
    id: "elevenlabs",
    image: "/tool-screenshots/elevenlabs.png",
    logo: "/logo/elevenlabs.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice cloning", "multilingual", "dubbing"],
    rating: 4.8,
    visits: 2500000,
    dateAdded: "2023-01-15",
    isPremium: 'Free'
  },
  {
    name: "Murf.ai",
    description: "Professional AI voiceover platform for creating lifelike voices and presentations.",
    url: "https://murf.ai",
    id: "murf-ai",
    image: "/tool-screenshots/murf-ai.png",
    logo: "/logo/murf-ai.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voiceover", "presentations", "text-to-speech"],
    rating: 4.6,
    visits: 1800000,
    dateAdded: "2023-02-20",
    isPremium: 'Free'
  },
  {
    name: "Lovo",
    description: "AI-powered voice editing and narration platform for content creation.",
    url: "https://lovo.ai",
    id: "lovo",
    image: "/tool-screenshots/lovo.png",
    logo: "/logo/lovo.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice editing", "narration", "content creation"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2023-03-10",
    isPremium: 'Free'
  },
  {
    name: "Voice.ai",
    description: "Real-time AI voice changer for streaming and content creation.",
    url: "https://voice.ai",
    id: "voice-ai",
    image: "/tool-screenshots/voice-ai.png",
    logo: "/logo/voice-ai.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice changer", "streaming", "real-time"],
    rating: 4.3,
    visits: 1200000,
    dateAdded: "2023-04-05",
    isPremium: 'Free'
  },
  {
    name: "Uberduck",
    description: "AI platform for creating custom voiceovers and music synthesis.",
    url: "https://uberduck.ai",
    id: "uberduck",
    image: "/tool-screenshots/uberduck.png",
    logo: "/logo/uberduck.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voiceovers", "music synthesis", "custom voices"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2023-05-01",
    isPremium: 'Free'
  },
  {
    name: "Descript",
    description: "All-in-one audio and video editing platform with AI-powered transcription and editing capabilities.",
    url: "https://descript.com",
    id: "descript",
    image: "/tool-screenshots/descript.png",
    logo: "/logo/descript.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "podcasting", "transcription", "editing"],
    rating: 4.7,
    visits: 2000000,
    dateAdded: "2023-01-01",
    isPremium: 'Free'
  },
  {
    name: "Adobe Podcast Enhance",
    description: "AI-powered audio enhancement tool for removing noise and improving speech clarity.",
    url: "https://podcast.adobe.com",
    id: "adobe-podcast-enhance",
    image: "/tool-screenshots/adobe-podcast-enhance.png",
    logo: "/logo/adobe-podcast-enhance.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "noise removal", "speech clarity", "enhancement"],
    rating: 4.6,
    visits: 1500000,
    dateAdded: "2023-02-15",
    isPremium: 'Free'
  },
  {
    name: "Krisp",
    description: "Real-time AI noise cancellation for meetings and live calls.",
    url: "https://krisp.ai",
    id: "krisp",
    image: "/tool-screenshots/krisp.png",
    logo: "/logo/krisp.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "noise cancellation", "meetings", "live calls"],
    rating: 4.8,
    visits: 3000000,
    dateAdded: "2022-12-01",
    isPremium: 'Free'
  },
  {
    name: "Auphonic",
    description: "Automated audio post-production and leveling tool.",
    url: "https://auphonic.com",
    id: "auphonic",
    image: "/tool-screenshots/auphonic.png",
    logo: "/logo/auphonic.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "audio leveling", "post-production", "automation"],
    rating: 4.5,
    visits: 800000,
    dateAdded: "2023-03-20",
    isPremium: 'Free'
  },
  {
    name: "Izotope Cascadia",
    description: "Professional AI-powered sound design and audio effects tool.",
    url: "https://izotope.com/cascadia",
    id: "izotope-cascadia",
    image: "/tool-screenshots/izotope-cascadia.png",
    logo: "/logo/izotope-cascadia.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "sound design", "audio effects", "professional"],
    rating: 4.7,
    visits: 1000000,
    dateAdded: "2023-04-10",
    isPremium: 'Free'
  },
  {
    name: "AIVA",
    description: "AI music composer for creating emotional soundtracks and film scores.",
    url: "https://aiva.ai",
    id: "aiva",
    image: "/tool-screenshots/aiva.png",
    logo: "/logo/aiva.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "soundtrack", "emotional music", "film scores"],
    rating: 4.6,
    visits: 1200000,
    dateAdded: "2023-01-20",
    isPremium: 'Free'
  },
  {
    name: "WavTool",
    description: "Browser-based AI digital audio workstation for music composition.",
    url: "https://wavtool.com",
    id: "wavtool",
    image: "/tool-screenshots/wavtool.png",
    logo: "/logo/wavtool.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "browser DAW", "composition", "music creation"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2023-04-20",
    isPremium: 'Free'
  },
  {
    name: "Suno",
    description: "AI-powered text-to-music generator with genre blending capabilities.",
    url: "https://suno.ai",
    id: "suno",
    image: "/tool-screenshots/suno.png",
    logo: "/logo/suno.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "text-to-music", "genre blending", "composition"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2023-05-10",
    isPremium: 'Free'
  },
  {
    name: "Whisper",
    description: "OpenAI's open-source speech recognition system for accurate transcription.",
    url: "https://github.com/openai/whisper",
    id: "whisper",
    image: "/tool-screenshots/whisper.png",
    logo: "/logo/whisper.png",
    categories: ["audio"],
    subcategory: "transcription",
    tags: ["AI", "speech-to-text", "open source", "transcription"],
    rating: 4.8,
    visits: 2500000,
    dateAdded: "2022-09-20",
    isPremium: 'Free'
  },
  {
    name: "Podcastle",
    description: "All-in-one podcasting platform with AI voice cloning and editing features.",
    url: "https://podcastle.ai",
    id: "podcastle",
    image: "/tool-screenshots/podcastle.png",
    logo: "/logo/podcastle.png",
    categories: ["audio"],
    subcategory: "transcription",
    tags: ["AI", "podcasting", "voice cloning", "editing"],
    rating: 4.6,
    visits: 1000000,
    dateAdded: "2023-03-01",
    isPremium: 'Free'
  },
  {
    name: "Midjourney",
    description: "Generates high-quality images from text prompts, popular among artists.",
    url: "https://www.midjourney.com",
    id: "midjourney",
    image: "/tool-screenshots/midjourney.png",
    logo: "/logo/midjourney.png",
    categories: ["image"],
    subcategory: "Artistic Image Generation",
    tags: ["art", "concept_design", "high_quality"],
    rating: 4.8,
    visits: 3500000,
    dateAdded: "2022-07-12",
    isPremium: "Premium"
  },
  {
    name: "DALL·E",
    description: "OpenAI's model creating images from textual descriptions, integrated with ChatGPT.",
    url: "https://openai.com/dall-e",
    id: "dalle",
    image: "/tool-screenshots/dalle.png",
    logo: "/logo/dalle.png",
    categories: ["image"],
    subcategory: "Text-to-Image Generation",
    tags: ["text_to_image", "illustrations"],
    rating: 4.7,
    visits: 28700,
    dateAdded: "2021-01-05",
    isPremium: "Freemium"
  },
  {
    name: "Adobe Firefly",
    description: "Adobe's AI tool for generating images and text effects, part of Creative Cloud.",
    url: "https://firefly.adobe.com",
    id: "adobe-firefly",
    image: "/tool-screenshots/adobe-firefly.png",
    logo: "/logo/adobe-firefly.png",
    categories: ["image"],
    subcategory: "Commercial Image Design",
    tags: ["adobe", "generative_fill", "branding"],
    rating: 4.6,
    visits: 318400000,
    dateAdded: "2023-03-21",
    isPremium: "Freemium"
  },
  {
    name: "Canva Magic Design",
    description: "AI-powered design assistant integrated with Canva for creating visual assets.",
    url: "https://www.canva.com/magic-design",
    id: "canva-magic-design",
    image: "/tool-screenshots/canva-magic-design.png",
    logo: "/logo/canva.png",
    categories: ["image"],
    subcategory: "Graphic Design Assistant",
    tags: ["templates", "design_assistant", "creative"],
    rating: 4.5,
    visits: 5000000,
    dateAdded: "2023-10-01",
    isPremium: "Freemium"
  },
  {
    name: "Leonardo.Ai",
    description: "AI platform for generating game assets, concept art, and illustrations.",
    url: "https://leonardo.ai",
    id: "leonardo-ai",
    image: "/tool-screenshots/leonardo-ai.png",
    logo: "/logo/leonardo-ai.png",
    categories: ["image"],
    subcategory: "Concept Art Generation",
    tags: ["game_assets", "concept_art", "illustration"],
    rating: 4.4,
    visits: 16800000,
    dateAdded: "2023-05-15",
    isPremium: "Freemium"
  },
  {
    name: "Recraft",
    description: "AI design tool for generating vector illustrations and UI assets.",
    url: "https://www.recraft.ai",
    id: "recraft",
    image: "/tool-screenshots/recraft.png",
    logo: "/logo/recraft.png",
    categories: ["image"],
    subcategory: "Vector Design Generation",
    tags: ["vector", "illustration", "branding_assets"],
    rating: 4.3,
    visits: 3800000,
    dateAdded: "2023-06-20",
    isPremium: "Freemium"
  },
  {
    name: "NightCafe",
    description: "A community-driven platform for generating artistic AI images.",
    url: "https://creator.nightcafe.studio",
    id: "nightcafe",
    image: "/tool-screenshots/nightcafe.png",
    logo: "/logo/nightcafe.png",
    categories: ["image"],
    subcategory: "Artistic Image Creation",
    tags: ["style_transfer", "AI_art", "community"],
    rating: 4.2,
    visits: 3900000,
    dateAdded: "2022-11-10",
    isPremium: "Freemium"
  },
  {
    name: "Fotor AI",
    description: "AI-powered photo editing and image generation platform.",
    url: "https://www.fotor.com/features/ai-image-generator",
    id: "fotor-ai",
    image: "/tool-screenshots/fotor-ai.png",
    logo: "/logo/fotor.png",
    categories: ["image"],
    subcategory: "Photo Editing & Generation",
    tags: ["photo_editing", "filters", "AI_portrait"],
    rating: 4.1,
    visits: 17800000,
    dateAdded: "2023-02-28",
    isPremium: "Freemium"
  },
  {
    name: "Lexica Art",
    description: "Prompt search engine and gallery for AI-generated images.",
    url: "https://lexica.art",
    id: "lexica-art",
    image: "/tool-screenshots/lexica-art.png",
    logo: "/logo/lexica-art.png",
    categories: ["image"],
    subcategory: "AI Image Search & Generation",
    tags: ["prompt_reference", "gallery", "image_variants"],
    rating: 4.0,
    visits: 755900,
    dateAdded: "2022-12-05",
    isPremium: "Freemium"
  },
  {
    name: "Playground AI",
    description: "Platform for creating and editing images using AI with various tools and filters.",
    url: "https://playgroundai.com",
    id: "playground-ai",
    image: "/tool-screenshots/playground-ai.png",
    logo: "/logo/playground-ai.png",
    categories: ["image"],
    subcategory: "Image Creation & Editing",
    tags: ["text_to_image", "inpainting", "style_filters"],
    rating: 4.0,
    visits: 171800,
    dateAdded: "2023-01-10",
    isPremium: "Freemium"
  },
  {
    name: "ChatGPT (GPT-4o)",
    description: "General-purpose AI assistant for writing, editing, and brainstorming.",
    url: "https://chat.openai.com",
    id: "chatgpt-gpt4o",
    image: "/tool-screenshots/chatgpt.png",
    logo: "/logo/chatgpt.png",
    categories: ["text"],
    subcategory: "General Writing Assistant",
    tags: ["chatbot", "content_creation", "summarization", "productivity", "brainstorming"],
    rating: 4.9,
    visits: 180000000,
    dateAdded: "2023-11-06",
    isPremium: "Freemium"
  },
  {
    name: "Claude 3",
    description: "Conversational AI with long memory and reliable, safe writing output.",
    url: "https://claude.ai",
    id: "claude-3",
    image: "/tool-screenshots/claude.png",
    logo: "/logo/claude.png",
    categories: ["text"],
    subcategory: "Research & Long-form Writing",
    tags: ["long_context", "safe_AI", "research", "creative_writing", "Q&A"],
    rating: 4.7,
    visits: 35000000,
    dateAdded: "2024-03-05",
    isPremium: "Freemium"
  },
  {
    name: "Gemini 1.5 Pro",
    description: "Google's advanced AI for factual writing and multilingual support.",
    url: "https://gemini.google.com",
    id: "gemini-1-5-pro",
    image: "/tool-screenshots/gemini-1-5-pro.png",
    logo: "/logo/gemini.png",
    categories: ["text"],
    subcategory: "Factual Writing & Multilingual",
    tags: ["translation", "academic", "factual", "multilingual", "summarization"],
    rating: 4.6,
    visits: 15000000,
    dateAdded: "2024-02-20",
    isPremium: "Freemium"
  },
  {
    name: "Jasper AI",
    description: "AI copywriter optimized for marketing, branding, and team collaboration.",
    url: "https://www.jasper.ai",
    id: "jasper-ai",
    image: "/tool-screenshots/jasper.png",
    logo: "/logo/jasper.png",
    categories: ["text"],
    subcategory: "Marketing Copy & Brand Voice",
    tags: ["copywriting", "marketing", "branding", "ads", "content_team"],
    rating: 4.5,
    visits: 1200000,
    dateAdded: "2021-05-10",
    isPremium: "Premium"
  },
  {
    name: "Copy.ai",
    description: "Fast content generation for sales emails, ads, and product descriptions.",
    url: "https://www.copy.ai",
    id: "copy-ai",
    image: "/tool-screenshots/copy-ai.png",
    logo: "/logo/copyai.png",
    categories: ["text"],
    subcategory: "Short-form & Email Copywriting",
    tags: ["social_media", "email_marketing", "ads", "sales_copy", "automation"],
    rating: 4.3,
    visits: 1700000,
    dateAdded: "2021-06-15",
    isPremium: "Freemium"
  },
  {
    name: "Writer.com",
    description: "Enterprise-grade writing assistant for brand-safe, compliant content.",
    url: "https://writer.com",
    id: "writer-com",
    image: "/tool-screenshots/writer-com.png",
    logo: "/logo/writer.png",
    categories: ["text"],
    subcategory: "Enterprise Content Governance",
    tags: ["compliance", "style_guide", "team_collaboration", "branding", "corporate"],
    rating: 4.4,
    visits: 950000,
    dateAdded: "2022-03-10",
    isPremium: "Premium"
  },
  {
    name: "INK for All",
    description: "SEO content optimization assistant.",
    url: "https://inkforall.com",
    id: "ink-for-all",
    image: "/tool-screenshots/ink-for-all.png",
    logo: "/logo/ink-for-all.png",
    categories: ["text"],
    subcategory: "SEO Content Optimization",
    tags: ["SEO", "content_marketing", "blogging", "rank_optimization", "writing_assistant"],
    rating: 4.2,
    visits: 620000,
    dateAdded: "2023-09-12",
    isPremium: "Freemium"
  },
  {
    name: "Wordtune",
    description: "AI-powered rewriting and tone enhancement assistant.",
    url: "https://www.wordtune.com",
    id: "wordtune",
    image: "/tool-screenshots/wordtune.png",
    logo: "/logo/wordtune.png",
    categories: ["text"],
    subcategory: "Text Rewriting & Refinement",
    tags: ["rephrasing", "tone_adjustment", "clarity", "grammar", "style_editing"],
    rating: 4.2,
    visits: 830000,
    dateAdded: "2020-09-25",
    isPremium: "Freemium"
  },
  {
    name: "QuillBot",
    description: "Academic writing assistant with paraphrasing and summarization.",
    url: "https://quillbot.com",
    id: "quillbot",
    image: "/tool-screenshots/quillbot.png",
    logo: "/logo/quillbot.png",
    categories: ["text"],
    subcategory: "Academic Writing & Paraphrasing",
    tags: ["paraphrasing", "summarizing", "citation", "academic", "plagiarism_check"],
    rating: 4.4,
    visits: 2400000,
    dateAdded: "2018-10-01",
    isPremium: "Freemium"
  },
  {
    name: "Sudowrite",
    description: "Creative writing tool for fiction authors and storytellers.",
    url: "https://www.sudowrite.com",
    id: "sudowrite",
    image: "/tool-screenshots/sudowrite.png",
    logo: "/logo/sudowrite.png",
    categories: ["text"],
    subcategory: "Creative & Fiction Writing",
    tags: ["storytelling", "novel", "fiction", "creative", "character_generation"],
    rating: 4.6,
    visits: 450000,
    dateAdded: "2021-12-05",
    isPremium: "Premium"
  },
  {
    name: "Writesonic",
    description: "All-in-one AI platform for marketing content and chatbots.",
    url: "https://writesonic.com",
    id: "writesonic",
    image: "/tool-screenshots/writesonic.png",
    logo: "/logo/writesonic.png",
    categories: ["text"],
    subcategory: "Multi-Tool for Marketing Teams",
    tags: ["AI_writer", "chatbot", "image_generation", "landing_pages", "bulk_content"],
    rating: 4.3,
    visits: 1700000,
    dateAdded: "2021-07-22",
    isPremium: "Freemium"
  },
  {
    name: "Anyword",
    description: "Ad copy and SEO tool with predictive performance scoring.",
    url: "https://anyword.com",
    id: "anyword",
    image: "/tool-screenshots/anyword.png",
    logo: "/logo/anyword.png",
    categories: ["text"],
    subcategory: "Predictive Ad Copywriting",
    tags: ["performance_score", "ads", "marketing_AI", "conversion_optimization", "A/B_testing"],
    rating: 4.5,
    visits: 980000,
    dateAdded: "2022-08-18",
    isPremium: "Premium"
  },
  {
    name: "Notion AI",
    description: "Built-in AI assistant for summarizing and generating content within Notion.",
    url: "https://www.notion.so/product/ai",
    id: "notion-ai",
    image: "/tool-screenshots/notion-ai.png",
    logo: "/logo/notion.png",
    categories: ["text"],
    subcategory: "Note-Taking & Productivity",
    tags: ["note_taking", "task_management", "summarization", "meeting_notes", "knowledge_management"],
    rating: 4.6,
    visits: 30000000,
    dateAdded: "2023-02-01",
    isPremium: "Freemium"
  },
  {
    name: "Runway",
    description: "AI-powered video editor and generator with Gen-2 and text-to-video capabilities.",
    url: "https://runwayml.com",
    id: "runway",
    image: "/tool-screenshots/runway.png",
    logo: "/logo/runway.png",
    categories: ["video"],
    subcategory: "AI Video Editing & Generation",
    tags: ["video_editing", "genAI", "green_screen", "style_transfer", "inpainting"],
    rating: 4.5,
    visits: 8100000,
    dateAdded: "2022-11-01",
    isPremium: "Freemium"
  },
  {
    name: "Pictory",
    description: "Convert scripts or articles into shareable videos using AI.",
    url: "https://pictory.ai",
    id: "pictory",
    image: "/tool-screenshots/pictory.png",
    logo: "/logo/pictory.png",
    categories: ["video"],
    subcategory: "Script/Text to Video Automation",
    tags: ["text_to_video", "content_repurposing", "video_summarization", "social_media"],
    rating: 4.4,
    visits: 2400000,
    dateAdded: "2022-06-10",
    isPremium: "Freemium"
  },
  {
    name: "Descript",
    description: "All-in-one video & audio editor with AI transcription and overdubbing.",
    url: "https://www.descript.com",
    id: "descript",
    image: "/tool-screenshots/descript.png",
    logo: "/logo/descript.png",
    categories: ["video"],
    subcategory: "Audio & Video Editing with Transcription",
    tags: ["podcast_video", "transcription", "overdub", "screen_recording", "multi_tool"],
    rating: 4.6,
    visits: 3100000,
    dateAdded: "2021-05-01",
    isPremium: "Freemium"
  },
  {
    name: "Fliki",
    description: "Generate videos with voiceovers from scripts, blogs, or tweets.",
    url: "https://fliki.ai",
    id: "fliki",
    image: "/tool-screenshots/fliki.png",
    logo: "/logo/fliki.png",
    categories: ["video"],
    subcategory: "Text-to-Video with Voiceover",
    tags: ["text_to_video", "voiceover", "short_form_video", "social_clips", "branding"],
    rating: 4.5,
    visits: 1900000,
    dateAdded: "2023-01-05",
    isPremium: "Freemium"
  },
  {
    name: "CapCut",
    description: "TikTok's official video editing tool with AI features and templates.",
    url: "https://www.capcut.com",
    id: "capcut",
    image: "/tool-screenshots/capcut.png",
    logo: "/logo/capcut.png",
    categories: ["video"],
    subcategory: "Consumer-Level AI Video Editing",
    tags: ["video_templates", "shorts", "filters", "background_removal", "mobile_editing"],
    rating: 4.4,
    visits: 45000000,
    dateAdded: "2021-03-15",
    isPremium: "Free"
  },
  {
    name: "Lumen5",
    description: "Turn blog posts into engaging marketing videos using AI.",
    url: "https://www.lumen5.com",
    id: "lumen5",
    image: "/tool-screenshots/lumen5.png",
    logo: "/logo/lumen5.png",
    categories: ["video"],
    subcategory: "AI Marketing Video Builder",
    tags: ["promo_videos", "content_marketing", "drag_and_drop", "automation", "text_overlay"],
    rating: 4.2,
    visits: 616700,
    dateAdded: "2020-12-01",
    isPremium: "Freemium"
  },
  {
    name: "Veed.io",
    description: "Online video editing platform with subtitles, AI tools, and effects.",
    url: "https://www.veed.io",
    id: "veed-io",
    image: "/tool-screenshots/veed-io.png",
    logo: "/logo/veed.png",
    categories: ["video"],
    subcategory: "Online Video Editing + AI Tools",
    tags: ["subtitling", "auto_transcription", "filters", "branding", "reels"],
    rating: 4.3,
    visits: 10900000,
    dateAdded: "2021-02-15",
    isPremium: "Freemium"
  },
  {
    name: "Wisecut",
    description: "Auto-edit talking-head videos with jump cuts, subtitles, and background music.",
    url: "https://www.wisecut.video",
    id: "wisecut",
    image: "/tool-screenshots/wisecut.png",
    logo: "/logo/wisecut.png",
    categories: ["video"],
    subcategory: "Auto-Editing for Talking Heads",
    tags: ["jump_cut", "auto_subtitles", "music_sync", "YouTube", "e_learning"],
    rating: 4.2,
    visits: 32700,
    dateAdded: "2021-08-20",
    isPremium: "Freemium"
  },
  {
    name: "Animoto",
    description: "Create slideshows and marketing videos with templates and stock footage.",
    url: "https://animoto.com",
    id: "animoto",
    image: "/tool-screenshots/animoto.png",
    logo: "/logo/animoto.png",
    categories: ["video"],
    subcategory: "Template-Based Video Builder",
    tags: ["social_video", "slideshow", "ecommerce", "storyboarding", "templates"],
    rating: 4.1,
    visits: 533100,
    dateAdded: "2019-11-12",
    isPremium: "Freemium"
  },
  {
    name: "Colossyan",
    description: "Generate explainer and training videos with avatars and slides.",
    url: "https://www.colossyan.com",
    id: "colossyan",
    image: "/tool-screenshots/colossyan.png",
    logo: "/logo/colossyan.png",
    categories: ["video"],
    subcategory: "Training & Explainer Video Automation",
    tags: ["AI_presenters", "learning_videos", "HR_training", "compliance", "slides_to_video"],
    rating: 4.2,
    visits: 172000,
    dateAdded: "2023-05-10",
    isPremium: "Freemium"
  },
  {
    name: "Magisto",
    description: "AI-powered video creation from uploaded clips and photos.",
    url: "https://www.magisto.com",
    id: "magisto",
    image: "/tool-screenshots/magisto.png",
    logo: "/logo/magisto.png",
    categories: ["video"],
    subcategory: "Smart Video Editing from Clips",
    tags: ["mobile_editing", "AI_editing", "auto_clips", "highlight_reels", "social_sharing"],
    rating: 4.0,
    visits: 150200,
    dateAdded: "2020-04-17",
    isPremium: "Freemium"
  },
  {
    name: "HeyGen",
    description: "Create realistic talking avatar videos with voice sync and translation.",
    url: "https://www.heygen.com",
    id: "heygen",
    image: "/tool-screenshots/heygen.png",
    logo: "/logo/heygen.png",
    categories: ["video"],
    subcategory: "Avatar Videos with Lip Sync",
    tags: ["talking_avatar", "video_translation", "voice_sync", "corporate_videos", "influencer_tools"],
    rating: 4.5,
    visits: 4800000,
    dateAdded: "2023-06-01",
    isPremium: "Premium"
  },
  {
    name: "Databricks",
    description: "Unified data analytics platform for big data and AI workloads.",
    url: "https://www.databricks.com",
    id: "databricks",
    image: "/tool-screenshots/databricks.png",
    logo: "/logo/databricks.png",
    categories: ["data"],
    subcategory: "Data Lakehouse Platform",
    tags: ["big_data", "data_engineering", "machine_learning", "spark", "lakehouse"],
    rating: 4.8,
    visits: 3850000,
    dateAdded: "2023-05-15",
    isPremium: "Premium"
  },
  {
    name: "Tableau",
    description: "Interactive data visualization software for business intelligence.",
    url: "https://www.tableau.com",
    id: "tableau",
    image: "/tool-screenshots/tableau.png",
    logo: "/logo/tableau.png",
    categories: ["data"],
    subcategory: "Data Visualization",
    tags: ["data_visualization", "business_intelligence", "dashboards", "analytics"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2022-11-20",
    isPremium: "Premium"
  },
  {
    name: "Microsoft Power BI",
    description: "Business analytics service providing interactive visualizations.",
    url: "https://powerbi.microsoft.com",
    id: "power-bi",
    image: "/tool-screenshots/power-bi.png",
    logo: "/logo/power-bi.png",
    categories: ["data"],
    subcategory: "Business Intelligence",
    tags: ["data_analysis", "reporting", "dashboards", "microsoft"],
    rating: 4.6,
    visits: 3200000,
    dateAdded: "2022-09-10",
    isPremium: "Freemium"
  },
  {
    name: "Julius AI",
    description: "AI assistant for data analysis and visualization.",
    url: "https://www.julius.ai",
    id: "julius-ai",
    image: "/tool-screenshots/julius-ai.png",
    logo: "/logo/julius-ai.png",
    categories: ["data"],
    subcategory: "AI Data Assistant",
    tags: ["data_analysis", "ai_assistant", "visualization", "natural_language"],
    rating: 4.4,
    visits: 80000,
    dateAdded: "2023-06-12",
    isPremium: "Freemium"
  },
  {
    name: "Simple Analytics",
    description: "Privacy-friendly analytics tool without cookies or tracking.",
    url: "https://simpleanalytics.com",
    id: "simple-analytics",
    image: "/tool-screenshots/simple-analytics.png",
    logo: "/logo/simple-analytics.png",
    categories: ["data"],
    subcategory: "Web Analytics",
    tags: ["privacy", "analytics", "web_traffic", "gdpr_compliance"],
    rating: 4.3,
    visits: 60000,
    dateAdded: "2022-08-18",
    isPremium: "Premium"
  },
  {
    name: "Akkio",
    description: "AI platform for building and deploying predictive models.",
    url: "https://www.akkio.com",
    id: "akkio",
    image: "/tool-screenshots/akkio.png",
    logo: "/logo/akkio.png",
    categories: ["data"],
    subcategory: "Predictive Analytics",
    tags: ["machine_learning", "predictive_models", "no_code", "data_analysis"],
    rating: 4.5,
    visits: 120000,
    dateAdded: "2023-01-22",
    isPremium: "Freemium"
  },
  {
    name: "MonkeyLearn",
    description: "Text analysis tool for extracting insights from text data.",
    url: "https://monkeylearn.com",
    id: "monkeylearn",
    image: "/tool-screenshots/monkeylearn.png",
    logo: "/logo/monkeylearn.png",
    categories: ["data"],
    subcategory: "Text Analysis",
    tags: ["nlp", "text_analysis", "machine_learning", "data_extraction"],
    rating: 4.4,
    visits: 90000,
    dateAdded: "2022-10-30",
    isPremium: "Freemium"
  },
  {
    name: "Sisense",
    description: "Business intelligence software for complex data analysis.",
    url: "https://www.sisense.com",
    id: "sisense",
    image: "/tool-screenshots/sisense.png",
    logo: "/logo/sisense.png",
    categories: ["data"],
    subcategory: "Business Intelligence",
    tags: ["data_integration", "analytics", "dashboards", "big_data"],
    rating: 4.6,
    visits: 1100000,
    dateAdded: "2022-07-14",
    isPremium: "Premium"
  },
  {
    name: "Kanaries",
    description: "AI-powered data exploration and visualization tool.",
    url: "https://kanaries.net",
    id: "kanaries",
    image: "/tool-screenshots/kanaries.png",
    logo: "/logo/kanaries.png",
    categories: ["data"],
    subcategory: "Data Exploration",
    tags: ["data_visualization", "ai_assistant", "exploratory_analysis", "charts"],
    rating: 4.3,
    visits: 50000,
    dateAdded: "2023-04-08",
    isPremium: "Freemium"
  },
  {
    name: "GitHub Copilot",
    description: "AI pair programmer that suggests code snippets and entire functions in real-time.",
    url: "https://github.com/features/copilot",
    id: "github-copilot",
    image: "/tool-screenshots/github-copilot.png",
    logo: "/logo/github-copilot.png",
    categories: ["coding"],
    subcategory: "Code Completion",
    tags: ["AI", "code_completion", "pair_programming", "IDE_integration"],
    rating: 4.8,
    visits: 5000000,
    dateAdded: "2021-06-29",
    isPremium: "Freemium"
  },
  {
    name: "Tabnine",
    description: "AI code completion tool that supports multiple languages and IDEs.",
    url: "https://www.tabnine.com",
    id: "tabnine",
    image: "/tool-screenshots/tabnine.png",
    logo: "/logo/tabnine.png",
    categories: ["coding"],
    subcategory: "Code Completion",
    tags: ["AI", "code_completion", "multi_language", "IDE_support"],
    rating: 4.5,
    visits: 1200000,
    dateAdded: "2019-02-15",
    isPremium: "Freemium"
  },
  {
    name: "Amazon CodeWhisperer",
    description: "AI coding companion that provides code recommendations based on natural language comments.",
    url: "https://aws.amazon.com/codewhisperer/",
    id: "amazon-codewhisperer",
    image: "/tool-screenshots/amazon-codewhisperer.png",
    logo: "/logo/amazon-codewhisperer.png",
    categories: ["coding"],
    subcategory: "Code Generation",
    tags: ["AI", "code_generation", "AWS", "natural_language"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2022-06-22",
    isPremium: "Freemium"
  },
  {
    name: "Replit Ghostwriter",
    description: "AI-powered code completion and generation tool integrated into Replit's online IDE.",
    url: "https://replit.com/site/ghostwriter",
    id: "replit-ghostwriter",
    image: "/tool-screenshots/replit-ghostwriter.png",
    logo: "/logo/replit-ghostwriter.png",
    categories: ["coding"],
    subcategory: "Online IDE",
    tags: ["AI", "code_completion", "online_IDE", "collaboration"],
    rating: 4.6,
    visits: 2500000,
    dateAdded: "2023-03-10",
    isPremium: "Premium"
  },
  {
    name: "Codeium",
    description: "AI-powered code generation tool that supports multiple programming languages.",
    url: "https://codeium.com",
    id: "codeium",
    image: "/tool-screenshots/codeium.png",
    logo: "/logo/codeium.png",
    categories: ["coding"],
    subcategory: "Code Generation",
    tags: ["AI", "code_generation", "multi_language", "IDE_integration"],
    rating: 4.4,
    visits: 300000,
    dateAdded: "2022-09-15",
    isPremium: "Freemium"
  },
  {
    name: "Sourcery",
    description: "AI tool that refactors Python code to improve readability and performance.",
    url: "https://sourcery.ai",
    id: "sourcery",
    image: "/tool-screenshots/sourcery.png",
    logo: "/logo/sourcery.png",
    categories: ["coding"],
    subcategory: "Code Refactoring",
    tags: ["AI", "code_refactoring", "Python", "performance"],
    rating: 4.1,
    visits: 150000,
    dateAdded: "2020-07-10",
    isPremium: "Freemium"
  },
  {
    name: "DeepCode",
    description: "AI-powered code review tool that detects bugs and security vulnerabilities.",
    url: "https://www.deepcode.ai",
    id: "deepcode",
    image: "/tool-screenshots/deepcode.png",
    logo: "/logo/deepcode.png",
    categories: ["coding"],
    subcategory: "Code Review",
    tags: ["AI", "code_review", "bug_detection", "security"],
    rating: 4.5,
    visits: 200000,
    dateAdded: "2019-11-05",
    isPremium: "Freemium"
  },
  {
    name: "Codiga",
    description: "AI tool that provides code analysis and automated code reviews.",
    url: "https://www.codiga.io",
    id: "codiga",
    image: "/tool-screenshots/codiga.png",
    logo: "/logo/codiga.png",
    categories: ["coding"],
    subcategory: "Code Analysis",
    tags: ["AI", "code_analysis", "code_review", "automation"],
    rating: 4.3,
    visits: 100000,
    dateAdded: "2021-01-18",
    isPremium: "Freemium"
  },
  {
    name: "Figma AI",
    description: "Collaborative interface design tool with AI-powered features for design suggestions and automation.",
    url: "https://www.figma.com/",
    id: "figma-ai",
    image: "/tool-screenshots/figma-ai.png",
    logo: "/logo/figma.png",
    categories: ["design"],
    subcategory: "UI/UX Design",
    tags: ["ui_design", "ux_design", "prototyping", "collaboration", "design_systems"],
    rating: 4.6,
    visits: 40000000,
    dateAdded: "2022-06-15",
    isPremium: "Freemium"
  },
  {
    name: "Uizard",
    description: "AI-powered design tool that transforms sketches and wireframes into digital designs.",
    url: "https://uizard.io/",
    id: "uizard",
    image: "/tool-screenshots/uizard.png",
    logo: "/logo/uizard.png",
    categories: ["design"],
    subcategory: "UI Design",
    tags: ["wireframing", "prototyping", "no_code", "ui_design", "collaboration"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2022-09-10",
    isPremium: "Freemium"
  },
  {
    name: "Looka",
    description: "AI-powered logo maker and brand identity design tool.",
    url: "https://looka.com/",
    id: "looka",
    image: "/tool-screenshots/looka.png",
    logo: "/logo/looka.png",
    categories: ["design"],
    subcategory: "Branding",
    tags: ["logo_design", "branding", "templates", "business_cards", "social_media_kits"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2021-05-20",
    isPremium: "Premium"
  },
  {
    name: "Designify",
    description: "AI tool for automatically enhancing product photos and removing backgrounds.",
    url: "https://www.designify.com/",
    id: "designify",
    image: "/tool-screenshots/designify.png",
    logo: "/logo/designify.png",
    categories: ["design"],
    subcategory: "Image Editing",
    tags: ["background_removal", "photo_enhancement", "ecommerce", "automation", "batch_processing"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2021-08-30",
    isPremium: "Freemium"
  },
  {
    name: "Let's Enhance",
    description: "AI-powered image upscaler and enhancer for improving image quality.",
    url: "https://letsenhance.io/",
    id: "lets-enhance",
    image: "/tool-screenshots/lets-enhance.png",
    logo: "/logo/lets-enhance.png",
    categories: ["design"],
    subcategory: "Image Enhancement",
    tags: ["image_upscaling", "photo_enhancement", "ecommerce", "print_quality", "batch_processing"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2019-12-10",
    isPremium: "Freemium"
  },
  {
    name: "Runway ML",
    description: "Creative toolkit offering AI-powered video editing and content creation features.",
    url: "https://runwayml.com/",
    id: "runway-ml",
    image: "/tool-screenshots/runway-ml.png",
    logo: "/logo/runway-ml.png",
    categories: ["design"],
    subcategory: "Video Editing",
    tags: ["video_editing", "green_screen", "style_transfer", "inpainting", "text_to_video"],
    rating: 4.6,
    visits: 8100000,
    dateAdded: "2022-11-01",
    isPremium: "Freemium"
  },
  {
    name: "Khroma",
    description: "AI-based color tool that learns your preferences to generate personalized color palettes.",
    url: "https://www.khroma.co/",
    id: "khroma",
    image: "/tool-screenshots/khroma.png",
    logo: "/logo/khroma.png",
    categories: ["design"],
    subcategory: "Color Tool",
    tags: ["color_palettes", "branding", "ui_design", "personalization", "inspiration"],
    rating: 4.3,
    visits: 500000,
    dateAdded: "2020-11-05",
    isPremium: "Free"
  }
];

export const mockTools = tools; 