import {
  Code,
  ImageIcon,
  MessageSquare,
  Mic,
  PenTool,
  Briefcase,
  Brain,
  Video,
  LineChart,
  Database,
} from "lucide-react"
import type { Tool, Category } from "./types"

// Mock categories with icons
export const categories: Category[] = [
  {
    id: "text-generation",
    name: "Text Generation",
    description: "AI tools for generating text content, including copywriting, content creation, and text completion.",
    icon: <MessageSquare className="h-4 w-4" />,
  },
  {
    id: "image-generation",
    name: "Image Generation",
    description: "Create images, art, and designs using AI-powered tools.",
    icon: <ImageIcon className="h-4 w-4" />,
  },
  {
    id: "coding",
    name: "Coding",
    description: "AI assistants and tools to help with programming, code generation, and debugging.",
    icon: <Code className="h-4 w-4" />,
  },
  {
    id: "audio",
    name: "Audio & Speech",
    description: "Tools for voice synthesis, transcription, and audio processing.",
    icon: <Mic className="h-4 w-4" />,
  },
  {
    id: "design",
    name: "Design",
    description: "AI-powered design tools for UI/UX, graphic design, and creative work.",
    icon: <PenTool className="h-4 w-4" />,
  },
  {
    id: "productivity",
    name: "Productivity",
    description: "Tools to enhance workflow, automate tasks, and improve efficiency.",
    icon: <Briefcase className="h-4 w-4" />,
  },
  {
    id: "research",
    name: "Research",
    description: "AI tools for data analysis, research assistance, and knowledge discovery.",
    icon: <Brain className="h-4 w-4" />,
  },
  {
    id: "video",
    name: "Video",
    description: "Tools for video generation, editing, and enhancement using AI.",
    icon: <Video className="h-4 w-4" />,
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "AI-powered analytics tools for data insights and business intelligence.",
    icon: <LineChart className="h-4 w-4" />,
  },
  {
    id: "data",
    name: "Data Processing",
    description: "Tools for data extraction, transformation, and processing with AI.",
    icon: <Database className="h-4 w-4" />,
  },
]

// Mock tools data
export const mockTools: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    description:
      "An AI language model that can engage in conversational dialogue and provide human-like text responses.",
    url: "https://chat.openai.com",
    image: "/placeholder.svg?height=300&width=500",
    logo: "/placeholder.svg?height=100&width=100",
    categories: ["text-generation", "productivity", "research"],
    tags: ["chat", "writing", "assistant"],
    rating: 4.8,
    visits: 15000000,
    dateAdded: "2022-11-30",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "An AI art generator that creates images from textual descriptions using advanced machine learning.",
    url: "https://midjourney.com",
    image: "/placeholder.svg?height=300&width=500",
    logo: "/placeholder.svg?height=100&width=100",
    categories: ["image-generation", "design"],
    tags: ["art", "images", "creative"],
    rating: 4.7,
    visits: 8500000,
    dateAdded: "2022-07-12",
    isPremium: true,
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description:
      "An AI pair programmer that helps you write better code by suggesting whole lines or blocks of code as you type.",
    url: "https://github.com/features/copilot",
    image: "/placeholder.svg?height=300&width=500",
    logo: "/placeholder.svg?height=100&width=100",
    categories: ["coding", "productivity"],
    tags: ["programming", "development", "assistant"],
    rating: 4.6,
    visits: 5000000,
    dateAdded: "2021-06-29",
    isPremium: true,
  },
  {
    id: "dall-e",
    name: "DALL-E",
    description: "An AI system that can create realistic images and art from a description in natural language.",
    url: "https://openai.com/dall-e-2",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["image-generation", "design"],
    rating: 4.5,
    visits: 7000000,
    dateAdded: "2021-01-05",
  },
  {
    id: "jasper",
    name: "Jasper",
    description:
      "AI content generator that helps you create marketing copy, social media posts, and long-form content.",
    url: "https://jasper.ai",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["text-generation", "productivity", "marketing"],
    rating: 4.4,
    visits: 3000000,
    dateAdded: "2021-02-15",
    isPremium: true,
  },
  {
    id: "claude",
    name: "Claude",
    description: "An AI assistant built by Anthropic to be helpful, harmless, and honest.",
    url: "https://claude.ai",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["text-generation", "research", "productivity"],
    rating: 4.7,
    visits: 4500000,
    dateAdded: "2023-03-14",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "An open-source AI art generator that creates detailed images from text descriptions.",
    url: "https://stability.ai",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["image-generation", "design"],
    rating: 4.5,
    visits: 6000000,
    dateAdded: "2022-08-22",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "AI voice generator with the most realistic and versatile AI speech software.",
    url: "https://elevenlabs.io",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["audio", "productivity"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2023-01-25",
    isPremium: true,
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "An AI-powered search engine that provides accurate and cited answers to your questions.",
    url: "https://perplexity.ai",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["research", "productivity"],
    rating: 4.5,
    visits: 3500000,
    dateAdded: "2022-12-05",
  },
  {
    id: "runway",
    name: "Runway",
    description: "AI magic tools for creators, including video generation, editing, and visual effects.",
    url: "https://runwayml.com",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["video", "design", "image-generation"],
    rating: 4.6,
    visits: 2800000,
    dateAdded: "2022-04-18",
    isPremium: true,
  },
  {
    id: "synthesia",
    name: "Synthesia",
    description:
      "AI video generation platform that turns text into professional-looking videos with AI-generated presenters.",
    url: "https://synthesia.io",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["video", "marketing"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2022-05-10",
    isPremium: true,
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "AI writing assistant integrated into Notion that helps you draft, edit, and summarize content.",
    url: "https://notion.so",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["text-generation", "productivity"],
    rating: 4.4,
    visits: 4200000,
    dateAdded: "2023-02-22",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Platform for machine learning with thousands of pre-trained models for various AI tasks.",
    url: "https://huggingface.co",
    image: "/placeholder.svg?height=300&width=500",
    categories: ["research", "coding", "data"],
    rating: 4.7,
    visits: 3200000,
    dateAdded: "2022-01-15",
  },
]
