import React from 'react'
import {
  Code,
  ImageIcon,
  MessageSquare,
  Mic,
  PenTool,
  Briefcase,
  Brain,
  Video,
  LineChart,
  Database,
  BarChart,
} from "lucide-react"
import type { Tool, Category } from "./types"

// Categories with icons
export const categories: Category[] = [
  {
    name: "Text",
    description: "AI tools for generating text content, including copywriting, content creation, and text completion.",
    icon: <MessageSquare className="h-4 w-4" />,
    id: "text"
  },
  {
    name: "Image",
    description: "Create images, art, and designs using AI-powered tools.",
    icon: <ImageIcon className="h-4 w-4" />,
    id: "image"
  },
  {
    name: "Coding",
    description: "AI assistants and tools to help with programming, code generation, and debugging.",
    icon: <Code className="h-4 w-4" />,
    id: "coding"
  },
  {
    name: "Audio",
    description: "Tools for voice synthesis, transcription, and audio processing.",
    icon: <Mic className="h-4 w-4" />,
    id: "audio"
  },
  {
    name: "Design",
    description: "AI-powered design tools for UI/UX, graphic design, and creative work.",
    icon: <PenTool className="h-4 w-4" />,
    id: "design"
  },
  {
    name: "Productivity",
    description: "Tools to enhance workflow, automate tasks, and improve efficiency.",
    icon: <Briefcase className="h-4 w-4" />,
    id: "productivity"
  },
  {
    name: "Research",
    description: "AI tools for data analysis, research assistance, and knowledge discovery.",
    icon: <Brain className="h-4 w-4" />,
    id: "research"
  },
  {
    name: "Video",
    description: "Tools for video generation, editing, and enhancement using AI.",
    icon: <Video className="h-4 w-4" />,
    id: "video"
  },
  {
    name: "Analytics",
    description: "AI-powered analytics tools for data insights and business intelligence.",
    icon: <LineChart className="h-4 w-4" />,
    id: "analytics"
  },
  {
    name: "Data Processing",
    description: "Tools for data extraction, transformation, and processing with AI.",
    icon: <Database className="h-4 w-4" />,
    id: "data-processing"
  },
  {
    name: "Marketing",
    description: "AI-powered tools for content creation, marketing automation, and campaign optimization.",
    icon: <BarChart className="h-4 w-4" />,
    id: "marketing"
  }
]

// Combined tools data
export const tools: Tool[] = [
{
    name: "Jasper (formerly Jarvis)",
    description: "AI content creation & copywriting platform.",
    url: "https://www.jasper.ai",
    id: "jasper",
    image: "/tool-screenshots/jasper.png",
    logo: "/logo/jasper.png",
    categories: ["marketing"],
    subcategory: "content-creation",
    tags: ["AI", "content", "copywriting"],
    rating: 4.7,
    visits: 2500000,
    dateAdded: "2021-01-15",
    isPremium: 'Free',
  },
{
    name: "Conversion.ai (Jasper AI)",
    description: "AI marketing & sales copy generation platform.",
    url: "https://www.conversion.ai",
    id: "conversion-ai",
    image: "/tool-screenshots/conversion-ai.png",
    logo: "/logo/conversion-ai.png",
    categories: ["marketing"],
    subcategory: "sales-copy",
    tags: ["AI", "marketing", "sales"],
    rating: 4.6,
    visits: 600000,
    dateAdded: "2021-10-15",
    isPremium: 'Free',
  },
{
    name: "INK (by Ink for All)",
    description: "AI-driven content optimization & SEO platform.",
    url: "https://inkforall.com",
    id: "ink",
    image: "/tool-screenshots/ink.png",
    logo: "/logo/ink.png",
    categories: ["marketing"],
    subcategory: "content-optimization",
    tags: ["AI", "SEO", "content"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2021-11-15",
    isPremium: 'Free',
  },
{
    name: "CopySmith",
    description: "AI content generation for marketing platform.",
    url: "https://copysmith.ai",
    id: "copysmith",
    image: "/tool-screenshots/copysmith.png",
    logo: "/logo/copysmith.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.3,
    visits: 400000,
    dateAdded: "2021-12-15",
    isPremium: 'Free',
  },
{
    name: "Copyscape",
    description: "AI-powered plagiarism detection & content validation platform.",
    url: "https://www.copyscape.com",
    id: "copyscape",
    image: "/tool-screenshots/copyscape.png",
    logo: "/logo/copyscape.png",
    categories: ["marketing"],
    subcategory: "content-validation",
    tags: ["AI", "plagiarism", "content"],
    rating: 4.4,
    visits: 350000,
    dateAdded: "2022-01-15",
    isPremium: 'Free',
  },
{
    name: "Grammarly",
    description: "AI-powered writing assistant that helps you write better by checking grammar, spelling, and style.",
    url: "https://www.grammarly.com",
    id: "grammarly",
    image: "/tool-screenshots/grammarly.png",
    logo: "/logo/grammarly.png",
    categories: ["text", "productivity"],
    subcategory: "grammar",
    tags: ["AI", "grammar", "proofreading", "editing"],
    rating: 4.7,
    visits: 12000000,
    dateAdded: "2020-09-15",
    isPremium: 'Free',
  },
{
    name: "QuillBot",
    description: "AI-powered paraphrasing tool that helps you rewrite and improve your text while maintaining its meaning.",
    url: "https://quillbot.com",
    id: "quillbot",
    image: "/tool-screenshots/quillbot.png",
    logo: "/logo/quillbot.png",
    categories: ["text", "productivity"],
    subcategory: "paraphrasing",
    tags: ["AI", "paraphrasing", "rewriting", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2021-03-20",
    isPremium: 'Free',
  },
{
    name: "ProWritingAid",
    description: "Comprehensive writing tool that helps you improve your writing style, grammar, and readability.",
    url: "https://prowritingaid.com",
    id: "prowritingaid",
    image: "/tool-screenshots/prowritingaid.png",
    logo: "/logo/prowritingaid.png",
    categories: ["text", "productivity"],
    subcategory: "style-editing",
    tags: ["AI", "style", "editing", "readability"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-06-15",
    isPremium: 'Free',
  },
{
    name: "Hemingway App",
    description: "AI-powered writing tool that helps you write clear, concise, and readable content.",
    url: "https://hemingwayapp.com",
    id: "hemingway-app",
    image: "/tool-screenshots/hemingway-app.png",
    logo: "/logo/hemingway-app.png",
    categories: ["text", "productivity"],
    subcategory: "readability",
    tags: ["AI", "readability", "writing", "style"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-20",
    isPremium: 'Free',
  },
{
    name: "Copy.ai",
    description: "AI-powered content and marketing copy generation platform.",
    url: "https://www.copy.ai",
    id: "copy-ai",
    image: "/tool-screenshots/copy-ai.png",
    logo: "/logo/copy-ai.png",
    categories: ["marketing"],
    subcategory: "content-generation",
    tags: ["AI", "content", "marketing"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2021-02-15",
    isPremium: 'Free',
  },
{
    name: "Synthesia",
    description: "AI video creators for marketing platform.",
    url: "https://www.synthesia.io",
    id: "synthesia",
    image: "/tool-screenshots/synthesia.png",
    logo: "/logo/synthesia.png",
    categories: ["marketing"],
    subcategory: "video-creation",
    tags: ["AI", "video", "marketing"],
    rating: 4.6,
    visits: 250000,
    dateAdded: "2022-03-15",
    isPremium: 'Free',
  },
{
    name: "Lumen5",
    description: "AI social media video content creation platform.",
    url: "https://lumen5.com",
    id: "lumen5",
    image: "/tool-screenshots/lumen5.png",
    logo: "/logo/lumen5.png",
    categories: ["marketing"],
    subcategory: "video-content",
    tags: ["AI", "video", "social media"],
    rating: 4.5,
    visits: 300000,
    dateAdded: "2022-02-15",
    isPremium: 'Free',
  },
{
    name: "Mem",
    description: "AI-powered note organization and intelligent retrieval platform.",
    url: "https://mem.ai",
    id: "mem",
    image: "/tool-screenshots/mem.png",
    logo: "/logo/mem.png",
    categories: ["productivity"],
    subcategory: "note-organization",
    tags: ["AI", "notes", "organization"],
    rating: 4.1,
    visits: 3000,
    dateAdded: "2026-11-15",
    isPremium: 'Free',
  },
{
    name: "Hugo AI",
    description: "Knowledge management and AI writing assistant.",
    url: "https://hugo.ai",
    id: "hugo-ai",
    image: "/tool-screenshots/hugo-ai.png",
    logo: "/logo/hugo-ai.png",
    categories: ["productivity"],
    subcategory: "knowledge-management",
    tags: ["AI", "knowledge", "writing"],
    rating: 4.3,
    visits: 6000,
    dateAdded: "2026-07-15",
    isPremium: 'Free',
  },
{
    name: "AI Dungeon",
    description: "Storytelling and creative writing AI for entertainment and inspiration.",
    url: "https://aidungeon.io",
    id: "ai-dungeon",
    image: "/tool-screenshots/ai-dungeon.png",
    logo: "/logo/ai-dungeon.png",
    categories: ["productivity"],
    subcategory: "creative-writing",
    tags: ["AI", "storytelling", "creativity"],
    rating: 4.0,
    visits: 10000,
    dateAdded: "2026-03-15",
    isPremium: 'Free',
  },
{
    name: "Stable Diffusion",
    description: "Open-source AI model for generating high-quality images from text descriptions.",
    url: "https://stability.ai",
    id: "stable-diffusion",
    image: "/tool-screenshots/stable-diffusion.png",
    logo: "/logo/stable-diffusion.png",
    categories: ["image"],
    subcategory: "open-source",
    tags: ["AI", "open-source", "art", "creative"],
    rating: 4.5,
    visits: 6000000,
    dateAdded: "2022-08-22",
    isPremium: 'Free',
  },
{
    name: "Adobe Firefly",
    description: "Adobe's AI-powered tool for creating creative assets and image design.",
    url: "https://firefly.adobe.com",
    id: "adobe-firefly",
    image: "/tool-screenshots/adobe-firefly.png",
    logo: "/logo/adobe-firefly.png",
    categories: ["image", "design"],
    subcategory: "creative-assets",
    tags: ["AI", "Adobe", "graphic design"],
    rating: 4.7,
    visits: 5000000,
    dateAdded: "2023-03-21",
    isPremium: 'Free',
  },
{
    name: "Canva AI",
    description: "AI-powered graphic design platform for creating professional images and templates.",
    url: "https://canva.com",
    id: "canva-ai",
    image: "/tool-screenshots/canva-ai.png",
    logo: "/logo/canva-ai.png",
    categories: ["image", "design"],
    subcategory: "graphic-design",
    tags: ["AI", "design", "graphics", "templates"],
    rating: 4.6,
    visits: 8000000,
    dateAdded: "2023-01-15",
    isPremium: 'Free',
  },
{
    name: "Artbreeder",
    description: "AI platform for genetic image merging and creative image generation.",
    url: "https://artbreeder.com",
    id: "artbreeder",
    image: "/tool-screenshots/artbreeder.png",
    logo: "/logo/artbreeder.png",
    categories: ["image"],
    subcategory: "image-blending",
    tags: ["AI", "image blending", "art"],
    rating: 4.3,
    visits: 1800000,
    dateAdded: "2021-08-01",
    isPremium: 'Free',
  },
{
    name: "Runway ML",
    description: "AI-powered video editing and generation platform for creative professionals.",
    url: "https://runwayml.com",
    id: "runway-ml",
    image: "/tool-screenshots/runway-ml.png",
    logo: "/logo/runway-ml.png",
    categories: ["video", "design"],
    subcategory: "video-generation",
    tags: ["AI", "video", "creative", "editing"],
    rating: 4.6,
    visits: 2200000,
    dateAdded: "2018-12-01",
    isPremium: 'Free',
  },
{
    name: "NightCafe Studio",
    description: "AI-powered platform for artistic image generation and style transfer.",
    url: "https://nightcafe.studio",
    id: "nightcafe-studio",
    image: "/tool-screenshots/nightcafe-studio.png",
    logo: "/logo/nightcafe-studio.png",
    categories: ["image"],
    subcategory: "artistic",
    tags: ["AI", "art", "style transfer"],
    rating: 4.2,
    visits: 1200000,
    dateAdded: "2021-12-01",
    isPremium: 'Free',
  },
{
    name: "Lensa AI",
    description: "AI-powered portrait and photo editing app.",
    url: "https://lensa-ai.com",
    id: "lensa-ai",
    image: "/tool-screenshots/lensa-ai.png",
    logo: "/logo/lensa-ai.png",
    categories: ["image"],
    subcategory: "portrait",
    tags: ["AI", "portrait", "editing"],
    rating: 4.5,
    visits: 4000000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
{
    name: "StarryAI",
    description: "AI platform for generating art and NFTs.",
    url: "https://starryai.com",
    id: "starryai",
    image: "/tool-screenshots/starryai.png",
    logo: "/logo/starryai.png",
    categories: ["image"],
    subcategory: "nft-art",
    tags: ["AI", "art", "NFTs", "creativity"],
    rating: 4.4,
    visits: 2000000,
    dateAdded: "2022-06-01",
    isPremium: 'Free'
  },
{
    name: "Jasper Art",
    description: "AI tool for generating content marketing images.",
    url: "https://jasper.ai/art",
    id: "jasper-art",
    image: "/tool-screenshots/jasper-art.png",
    logo: "/logo/jasper-art.png",
    categories: ["image", "marketing"],
    subcategory: "marketing",
    tags: ["AI", "marketing", "content", "art"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2022-04-01",
    isPremium: 'Free'
  },
{
    name: "Craiyon (formerly DALL·E Mini)",
    description: "Quick and accessible text-to-image generation tool.",
    url: "https://craiyon.com",
    id: "craiyon",
    image: "/tool-screenshots/craiyon.png",
    logo: "/logo/craiyon.png",
    categories: ["image"],
    subcategory: "quick-generation",
    tags: ["AI", "art", "quick generation"],
    rating: 4.1,
    visits: 3000000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
{
    name: "Deep Nostalgia",
    description: "AI tool for animating photos from still images.",
    url: "https://myheritage.com/deep-nostalgia",
    id: "deep-nostalgia",
    image: "/tool-screenshots/deep-nostalgia.png",
    logo: "/logo/deep-nostalgia.png",
    categories: ["image", "video"],
    subcategory: "animation",
    tags: ["AI", "animation", "photo"],
    rating: 4.3,
    visits: 2500000,
    dateAdded: "2022-01-01",
    isPremium: 'Free'
  },
{
    name: "FaceApp",
    description: "AI-powered app for facial transformations and edits.",
    url: "https://faceapp.com",
    id: "faceapp",
    image: "/tool-screenshots/faceapp.png",
    logo: "/logo/faceapp.png",
    categories: ["image"],
    subcategory: "face-editing",
    tags: ["AI", "faces", "editing"],
    rating: 4.4,
    visits: 3500000,
    dateAdded: "2021-12-01",
    isPremium: 'Free'
  },
{
    name: "Amazon CodeWhisperer",
    description: "AI-powered code generation tool integrated with AWS services.",
    url: "https://aws.amazon.com/codewhisperer",
    id: "amazon-codewhisperer",
    image: "/tool-screenshots/amazon-codewhisperer.png",
    logo: "/logo/amazon-codewhisperer.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "code", "automation", "AWS"],
    rating: 4.5,
    visits: 3000000,
    dateAdded: "2022-06-23",
    isPremium: 'Free'
  },
{
    name: "Replit Ghostwriter",
    description: "AI coding assistant integrated directly into the Replit IDE for seamless development.",
    url: "https://replit.com/ghostwriter",
    id: "replit-ghostwriter",
    image: "/tool-screenshots/replit-ghostwriter.png",
    logo: "/logo/replit-ghostwriter.png",
    categories: ["coding"],
    subcategory: "ide-integration",
    tags: ["AI", "IDE", "code generation", "collaboration"],
    rating: 4.3,
    visits: 1500000,
    dateAdded: "2023-01-10",
    isPremium: 'Free'
  },
{
    name: "DeepCode (Snyk Code)",
    description: "AI-driven code review and bug detection platform for improved code quality.",
    url: "https://snyk.io/product/snyk-code",
    id: "deepcode",
    image: "/tool-screenshots/deepcode.png",
    logo: "/logo/deepcode.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "bug fixing"],
    rating: 4.5,
    visits: 1800000,
    dateAdded: "2021-08-20",
    isPremium: 'Free'
  },
{
    name: "Kite",
    description: "AI-powered code completion and documentation tool for developers.",
    url: "https://kite.com",
    id: "kite",
    image: "/tool-screenshots/kite.png",
    logo: "/logo/kite.png",
    categories: ["coding"],
    subcategory: "code-assistance",
    tags: ["AI", "autocompletion", "documentation"],
    rating: 4.2,
    visits: 1500000,
    dateAdded: "2021-05-15",
    isPremium: 'Free'
  },
{
    name: "Codeium",
    description: "Real-time AI code completion tool for faster and more efficient coding.",
    url: "https://codeium.com",
    id: "codeium",
    image: "/tool-screenshots/codeium.png",
    logo: "/logo/codeium.png",
    categories: ["coding"],
    subcategory: "code-autocompletion",
    tags: ["AI", "IDE", "developer tools"],
    rating: 4.4,
    visits: 1200000,
    dateAdded: "2022-03-01",
    isPremium: 'Free'
  },
{
    name: "Sourcegraph",
    description: "AI-enhanced code search and intelligence platform for better code navigation.",
    url: "https://sourcegraph.com",
    id: "sourcegraph",
    image: "/tool-screenshots/sourcegraph.png",
    logo: "/logo/sourcegraph.png",
    categories: ["coding"],
    subcategory: "code-search",
    tags: ["AI", "codebase", "navigation"],
    rating: 4.6,
    visits: 2000000,
    dateAdded: "2021-11-15",
    isPremium: 'Free'
  },
{
    name: "Cogram",
    description: "AI-powered SQL code generation and analytics platform.",
    url: "https://cogram.com",
    id: "cogram",
    image: "/tool-screenshots/cogram.png",
    logo: "/logo/cogram.png",
    categories: ["coding", "data"],
    subcategory: "sql-generation",
    tags: ["AI", "SQL", "data analysis"],
    rating: 4.3,
    visits: 900000,
    dateAdded: "2022-02-15",
    isPremium: 'Free'
  },
{
    name: "PolyCoder",
    description: "Open-source large-scale code generator for various programming languages.",
    url: "https://github.com/VHellendoorn/Code-LMs",
    id: "polycoder",
    image: "/tool-screenshots/polycoder.png",
    logo: "/logo/polycoder.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "open-source", "models"],
    rating: 4.1,
    visits: 800000,
    dateAdded: "2022-04-01",
    isPremium: 'Free'
  },
{
    name: "WizardCoder",
    description: "Cloud-based AI coding helper for developers.",
    url: "https://wizardcoder.com",
    id: "wizardcoder",
    image: "/tool-screenshots/wizardcoder.png",
    logo: "/logo/wizardcoder.png",
    categories: ["coding"],
    subcategory: "cloud-coding",
    tags: ["AI", "cloud", "development tools"],
    rating: 4.2,
    visits: 700000,
    dateAdded: "2022-05-15",
    isPremium: 'Free'
  },
{
    name: "DeepDev",
    description: "AI-powered debugging and code correction tool.",
    url: "https://deepdev.io",
    id: "deepdev",
    image: "/tool-screenshots/deepdev.png",
    logo: "/logo/deepdev.png",
    categories: ["coding"],
    subcategory: "debugging",
    tags: ["AI", "debugging", "troubleshooting"],
    rating: 4.3,
    visits: 600000,
    dateAdded: "2022-06-01",
    isPremium: 'Free'
  },
{
    name: "Microsoft Turing",
    description: "Enterprise AI development models for large-scale applications.",
    url: "https://www.microsoft.com/en-us/ai/turing",
    id: "microsoft-turing",
    image: "/tool-screenshots/microsoft-turing.png",
    logo: "/logo/microsoft-turing.png",
    categories: ["coding"],
    subcategory: "enterprise-ai",
    tags: ["AI", "enterprise", "models"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2022-07-01",
    isPremium: 'Free'
  },
{
    name: "CodeT5",
    description: "Multi-language code understanding and generation model.",
    url: "https://github.com/salesforce/CodeT5",
    id: "codet5",
    image: "/tool-screenshots/codet5.png",
    logo: "/logo/codet5.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "T5", "models"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2022-08-15",
    isPremium: 'Free'
  },
{
    name: "AI4Code",
    description: "AI platform for automated code reviews and suggestions.",
    url: "https://ai4code.com",
    id: "ai4code",
    image: "/tool-screenshots/ai4code.png",
    logo: "/logo/ai4code.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "QA"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2022-10-01",
    isPremium: 'Free'
  },
{
    name: "ChatCode",
    description: "Interactive AI coding chatbot for developer support.",
    url: "https://chatcode.ai",
    id: "chatcode",
    image: "/tool-screenshots/chatcode.png",
    logo: "/logo/chatcode.png",
    categories: ["coding"],
    subcategory: "chatbot",
    tags: ["AI", "chatbot", "developer support"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2022-11-01",
    isPremium: 'Free'
  },
{
    name: "PyCaret",
    description: "AutoML platform for machine learning and coding pipelines.",
    url: "https://pycaret.org",
    id: "pycaret",
    image: "/tool-screenshots/pycaret.png",
    logo: "/logo/pycaret.png",
    categories: ["coding", "data"],
    subcategory: "automl",
    tags: ["AI", "AutoML", "Python"],
    rating: 4.5,
    visits: 1200000,
    dateAdded: "2022-12-01",
    isPremium: 'Free'
  },
{
    name: "DataRobot Code",
    description: "AI platform for code optimization and deployment.",
    url: "https://www.datarobot.com",
    id: "datarobot-code",
    image: "/tool-screenshots/datarobot-code.png",
    logo: "/logo/datarobot-code.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "deployment", "automation"],
    rating: 4.4,
    visits: 900000,
    dateAdded: "2023-01-01",
    isPremium: 'Free'
  },
{
    name: "CodeGen",
    description: "Transformer models for code synthesis and generation.",
    url: "https://github.com/salesforce/CodeGen",
    id: "codegen",
    image: "/tool-screenshots/codegen.png",
    logo: "/logo/codegen.png",
    categories: ["coding"],
    subcategory: "code-generation",
    tags: ["AI", "deep learning", "models"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2023-02-01",
    isPremium: 'Free'
  },
{
    name: "Sourcery",
    description: "AI-powered Python refactoring and code improvement tool.",
    url: "https://sourcery.ai",
    id: "sourcery",
    image: "/tool-screenshots/sourcery.png",
    logo: "/logo/sourcery.png",
    categories: ["coding"],
    subcategory: "refactoring",
    tags: ["AI", "Python", "refactoring"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2023-03-01",
    isPremium: 'Free'
  },
{
    name: "Kogito",
    description: "Enterprise automation platform with AI capabilities.",
    url: "https://kogito.kie.org",
    id: "kogito",
    image: "/tool-screenshots/kogito.png",
    logo: "/logo/kogito.png",
    categories: ["coding"],
    subcategory: "automation",
    tags: ["AI", "automation", "business"],
    rating: 4.1,
    visits: 300000,
    dateAdded: "2023-04-01",
    isPremium: 'Free'
  },
{
    name: "Jina AI",
    description: "Neural search and multimedia pipelines platform.",
    url: "https://jina.ai",
    id: "jina-ai",
    image: "/tool-screenshots/jina-ai.png",
    logo: "/logo/jina-ai.png",
    categories: ["coding", "data"],
    subcategory: "neural-search",
    tags: ["AI", "search", "neural network"],
    rating: 4.4,
    visits: 500000,
    dateAdded: "2023-05-01",
    isPremium: 'Free'
  },
{
    name: "Yellowbrick",
    description: "ML model visualization tool for code debugging.",
    url: "https://www.scikit-yb.org",
    id: "yellowbrick",
    image: "/tool-screenshots/yellowbrick.png",
    logo: "/logo/yellowbrick.png",
    categories: ["coding", "data"],
    subcategory: "visualization",
    tags: ["AI", "visualization", "ML"],
    rating: 4.0,
    visits: 200000,
    dateAdded: "2023-07-01",
    isPremium: 'Free'
  },
{
    name: "Semantic Kernel (Microsoft)",
    description: "AI SDK for automation and code integration.",
    url: "https://github.com/microsoft/semantic-kernel",
    id: "semantic-kernel",
    image: "/tool-screenshots/semantic-kernel.png",
    logo: "/logo/semantic-kernel.png",
    categories: ["coding"],
    subcategory: "sdk",
    tags: ["AI", "SDK", "automation"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2023-09-01",
    isPremium: 'Free'
  },
{
    name: "ML.NET",
    description: "Machine learning framework for C# and .NET developers.",
    url: "https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet",
    id: "ml-net",
    image: "/tool-screenshots/ml-net.png",
    logo: "/logo/ml-net.png",
    categories: ["coding", "data"],
    subcategory: "ml-framework",
    tags: ["AI", ".NET", "ML"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2023-10-01",
    isPremium: 'Free'
  },
{
    name: "Hugging Face Transformers",
    description: "Library of pre-trained models for code and NLP tasks.",
    url: "https://huggingface.co/docs/transformers",
    id: "huggingface-transformers",
    image: "/tool-screenshots/huggingface-transformers.png",
    logo: "/logo/huggingface-transformers.png",
    categories: ["coding", "data"],
    subcategory: "models",
    tags: ["AI", "transformers", "models"],
    rating: 4.7,
    visits: 3000000,
    dateAdded: "2023-11-01",
    isPremium: 'Free'
  },
{
    name: "Keras Tuner",
    description: "Hyperparameter optimization tool with AI capabilities.",
    url: "https://keras.io/keras_tuner",
    id: "keras-tuner",
    image: "/tool-screenshots/keras-tuner.png",
    logo: "/logo/keras-tuner.png",
    categories: ["coding", "data"],
    subcategory: "optimization",
    tags: ["AI", "hyperparameters", "ML"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2024-01-01",
    isPremium: 'Free'
  },
{
    name: "MLflow",
    description: "ML lifecycle management and deployment platform.",
    url: "https://mlflow.org",
    id: "mlflow",
    image: "/tool-screenshots/mlflow.png",
    logo: "/logo/mlflow.png",
    categories: ["coding", "data"],
    subcategory: "ml-ops",
    tags: ["AI", "lifecycle", "ML Ops"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2024-02-01",
    isPremium: 'Free'
  },
{
    name: "Google DeepMind AlphaCode",
    description: "AI system for competitive programming and code synthesis.",
    url: "https://deepmind.com/blog/article/Competitive-programming-with-AlphaCode",
    id: "alphacode",
    image: "/tool-screenshots/alphacode.png",
    logo: "/logo/alphacode.png",
    categories: ["coding"],
    subcategory: "code-synthesis",
    tags: ["AI", "synthesis", "deep learning"],
    rating: 4.8,
    visits: 2000000,
    dateAdded: "2024-03-01",
    isPremium: 'Free'
  },
{
    name: "ExaCode",
    description: "AI performance tuning and bug detection tool.",
    url: "https://exacode.ai",
    id: "exacode",
    image: "/tool-screenshots/exacode.png",
    logo: "/logo/exacode.png",
    categories: ["coding"],
    subcategory: "performance",
    tags: ["AI", "performance", "bug-finding"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2024-04-01",
    isPremium: 'Free'
  },
{
    name: "CodeComplete",
    description: "AI-driven code snippets and blocks library.",
    url: "https://codecomplete.ai",
    id: "codecomplete",
    image: "/tool-screenshots/codecomplete.png",
    logo: "/logo/codecomplete.png",
    categories: ["coding"],
    subcategory: "code-snippets",
    tags: ["AI", "snippets", "library"],
    rating: 4.2,
    visits: 500000,
    dateAdded: "2024-05-01",
    isPremium: 'Free'
  },
{
    name: "Debuild.co",
    description: "AI web app builder that generates code from prompts.",
    url: "https://debuild.co",
    id: "debuild",
    image: "/tool-screenshots/debuild.png",
    logo: "/logo/debuild.png",
    categories: ["coding"],
    subcategory: "web-development",
    tags: ["AI", "web development", "no-code"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2024-06-01",
    isPremium: 'Free'
  },
{
    name: "Chai ML",
    description: "AI assistant for coding suggestions and Q&A.",
    url: "https://chai.ml",
    id: "chai-ml",
    image: "/tool-screenshots/chai-ml.png",
    logo: "/logo/chai-ml.png",
    categories: ["coding"],
    subcategory: "chat-assistant",
    tags: ["AI", "chat", "suggestions"],
    rating: 4.1,
    visits: 300000,
    dateAdded: "2024-07-01",
    isPremium: 'Free'
  },
{
    name: "DeepAI Code Support",
    description: "AI-based code assistance and error fixing tool.",
    url: "https://deepai.org",
    id: "deepai-code-support",
    image: "/tool-screenshots/deepai-code-support.png",
    logo: "/logo/deepai-code-support.png",
    categories: ["coding"],
    subcategory: "code-assistance",
    tags: ["AI", "bug fixing"],
    rating: 4.0,
    visits: 200000,
    dateAdded: "2024-08-01",
    isPremium: 'Free'
  },
{
    name: "AI Developer Extensions",
    description: "Collection of IDE plugins for AI coding assistance.",
    url: "https://marketplace.visualstudio.com",
    id: "ai-developer-extensions",
    image: "/tool-screenshots/ai-developer-extensions.png",
    logo: "/logo/ai-developer-extensions.png",
    categories: ["coding"],
    subcategory: "ide-plugins",
    tags: ["AI", "IDE", "plugins"],
    rating: 4.2,
    visits: 600000,
    dateAdded: "2024-10-01",
    isPremium: 'Free'
  },
{
    name: "Replit AI",
    description: "Integrated AI coding environment for collaborative development.",
    url: "https://replit.com",
    id: "replit-ai",
    image: "/tool-screenshots/replit-ai.png",
    logo: "/logo/replit-ai.png",
    categories: ["coding"],
    subcategory: "ide",
    tags: ["AI", "IDE", "collaborative coding"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2024-12-01",
    isPremium: 'Free'
  },
{
    name: "CodeSandbox AI",
    description: "AI-assisted code sharing and editing platform.",
    url: "https://codesandbox.io",
    id: "codesandbox-ai",
    image: "/tool-screenshots/codesandbox-ai.png",
    logo: "/logo/codesandbox-ai.png",
    categories: ["coding"],
    subcategory: "web-ide",
    tags: ["AI", "web", "IDE"],
    rating: 4.3,
    visits: 900000,
    dateAdded: "2025-01-01",
    isPremium: 'Free'
  },
{
    name: "AI CodeReviewer",
    description: "AI-based code review and quality analysis tool.",
    url: "https://aicodereviewer.com",
    id: "ai-codereviewer",
    image: "/tool-screenshots/ai-codereviewer.png",
    logo: "/logo/ai-codereviewer.png",
    categories: ["coding"],
    subcategory: "code-review",
    tags: ["AI", "review", "QA"],
    rating: 4.2,
    visits: 700000,
    dateAdded: "2025-02-01",
    isPremium: 'Free'
  },
{
    name: "CodeSquire",
    description: "AI-powered technical documentation and code generation tool.",
    url: "https://codesquire.com",
    id: "codesquire",
    image: "/tool-screenshots/codesquire.png",
    logo: "/logo/codesquire.png",
    categories: ["coding"],
    subcategory: "documentation",
    tags: ["AI", "documentation", "developer tools"],
    rating: 4.3,
    visits: 800000,
    dateAdded: "2025-05-01",
    isPremium: 'Free'
  },
{
    name: "bayesianCode",
    description: "Probabilistic programming with AI optimization.",
    url: "https://bayesiancode.com",
    id: "bayesiancode",
    image: "/tool-screenshots/bayesiancode.png",
    logo: "/logo/bayesiancode.png",
    categories: ["coding", "data"],
    subcategory: "probabilistic",
    tags: ["AI", "probabilistic", "optimization"],
    rating: 4.1,
    visits: 400000,
    dateAdded: "2025-06-01",
    isPremium: 'Free'
  },
{
    name: "Program Synthesis Tools",
    description: "AI for automatic code generation from specifications.",
    url: "https://program-synthesis.org",
    id: "program-synthesis",
    image: "/tool-screenshots/program-synthesis.png",
    logo: "/logo/program-synthesis.png",
    categories: ["coding"],
    subcategory: "code-synthesis",
    tags: ["AI", "synthesis", "automation"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2025-09-01",
    isPremium: 'Free'
  },
{
    name: "Cursor",
    description: "AI-powered code completion and suggestions for developers.",
    url: "https://cursor.sh",
    id: "cursor",
    image: "/tool-screenshots/cursor.png",
    logo: "/logo/cursor.png",
    categories: ["coding"],
    subcategory: "code-completion",
    tags: ["AI", "completion", "IDE"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2025-10-01",
    isPremium: 'Free'
  },
{
    name: "ElevenLabs",
    description: "Advanced AI voice cloning and synthesis platform supporting multiple languages and dubbing capabilities.",
    url: "https://elevenlabs.io",
    id: "elevenlabs",
    image: "/tool-screenshots/elevenlabs.png",
    logo: "/logo/elevenlabs.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice cloning", "multilingual", "dubbing"],
    rating: 4.8,
    visits: 2500000,
    dateAdded: "2023-01-15",
    isPremium: 'Free',
  },
{
    name: "Murf.ai",
    description: "Professional AI voiceover platform for creating lifelike voices and presentations.",
    url: "https://murf.ai",
    id: "murf-ai",
    image: "/tool-screenshots/murf-ai.png",
    logo: "/logo/murf-ai.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voiceover", "presentations", "text-to-speech"],
    rating: 4.6,
    visits: 1800000,
    dateAdded: "2023-02-20",
    isPremium: 'Free',
  },
{
    name: "Lovo",
    description: "AI-powered voice editing and narration platform for content creation.",
    url: "https://lovo.ai",
    id: "lovo",
    image: "/tool-screenshots/lovo.png",
    logo: "/logo/lovo.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice editing", "narration", "content creation"],
    rating: 4.5,
    visits: 1500000,
    dateAdded: "2023-03-10",
    isPremium: 'Free',
  },
{
    name: "Voice.ai",
    description: "Real-time AI voice changer for streaming and content creation.",
    url: "https://voice.ai",
    id: "voice-ai",
    image: "/tool-screenshots/voice-ai.png",
    logo: "/logo/voice-ai.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voice changer", "streaming", "real-time"],
    rating: 4.3,
    visits: 1200000,
    dateAdded: "2023-04-05",
    isPremium: 'Free',
  },
{
    name: "Uberduck",
    description: "AI platform for creating custom voiceovers and music synthesis.",
    url: "https://uberduck.ai",
    id: "uberduck",
    image: "/tool-screenshots/uberduck.png",
    logo: "/logo/uberduck.png",
    categories: ["audio"],
    subcategory: "voice-generation",
    tags: ["AI", "voiceovers", "music synthesis", "custom voices"],
    rating: 4.4,
    visits: 1000000,
    dateAdded: "2023-05-01",
    isPremium: 'Free',
  },
{
    name: "Descript",
    description: "All-in-one audio and video editing platform with AI-powered transcription and editing capabilities.",
    url: "https://descript.com",
    id: "descript",
    image: "/tool-screenshots/descript.png",
    logo: "/logo/descript.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "podcasting", "transcription", "editing"],
    rating: 4.7,
    visits: 2000000,
    dateAdded: "2023-01-01",
    isPremium: 'Free',
  },
{
    name: "Adobe Podcast Enhance",
    description: "AI-powered audio enhancement tool for removing noise and improving speech clarity.",
    url: "https://podcast.adobe.com",
    id: "adobe-podcast-enhance",
    image: "/tool-screenshots/adobe-podcast-enhance.png",
    logo: "/logo/adobe-podcast-enhance.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "noise removal", "speech clarity", "enhancement"],
    rating: 4.6,
    visits: 1500000,
    dateAdded: "2023-02-15",
    isPremium: 'Free',
  },
{
    name: "Krisp",
    description: "Real-time AI noise cancellation for meetings and live calls.",
    url: "https://krisp.ai",
    id: "krisp",
    image: "/tool-screenshots/krisp.png",
    logo: "/logo/krisp.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "noise cancellation", "meetings", "live calls"],
    rating: 4.8,
    visits: 3000000,
    dateAdded: "2022-12-01",
    isPremium: 'Free',
  },
{
    name: "Auphonic",
    description: "Automated audio post-production and leveling tool.",
    url: "https://auphonic.com",
    id: "auphonic",
    image: "/tool-screenshots/auphonic.png",
    logo: "/logo/auphonic.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "audio leveling", "post-production", "automation"],
    rating: 4.5,
    visits: 800000,
    dateAdded: "2023-03-20",
    isPremium: 'Free',
  },
{
    name: "Izotope Cascadia",
    description: "Professional AI-powered sound design and audio effects tool.",
    url: "https://izotope.com/cascadia",
    id: "izotope-cascadia",
    image: "/tool-screenshots/izotope-cascadia.png",
    logo: "/logo/izotope-cascadia.png",
    categories: ["audio"],
    subcategory: "audio-editing",
    tags: ["AI", "sound design", "audio effects", "professional"],
    rating: 4.7,
    visits: 1000000,
    dateAdded: "2023-04-10",
    isPremium: 'Free',
  },
{
    name: "AIVA",
    description: "AI music composer for creating emotional soundtracks and film scores.",
    url: "https://aiva.ai",
    id: "aiva",
    image: "/tool-screenshots/aiva.png",
    logo: "/logo/aiva.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "soundtrack", "emotional music", "film scores"],
    rating: 4.6,
    visits: 1200000,
    dateAdded: "2023-01-20",
    isPremium: 'Free',
  },
{
    name: "WavTool",
    description: "Browser-based AI digital audio workstation for music composition.",
    url: "https://wavtool.com",
    id: "wavtool",
    image: "/tool-screenshots/wavtool.png",
    logo: "/logo/wavtool.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "browser DAW", "composition", "music creation"],
    rating: 4.3,
    visits: 700000,
    dateAdded: "2023-04-20",
    isPremium: 'Free',
  },
{
    name: "Suno",
    description: "AI-powered text-to-music generator with genre blending capabilities.",
    url: "https://suno.ai",
    id: "suno",
    image: "/tool-screenshots/suno.png",
    logo: "/logo/suno.png",
    categories: ["audio"],
    subcategory: "music-generation",
    tags: ["AI", "text-to-music", "genre blending", "composition"],
    rating: 4.4,
    visits: 800000,
    dateAdded: "2023-05-10",
    isPremium: 'Free',
  },
{
    name: "Whisper",
    description: "OpenAI's open-source speech recognition system for accurate transcription.",
    url: "https://github.com/openai/whisper",
    id: "whisper",
    image: "/tool-screenshots/whisper.png",
    logo: "/logo/whisper.png",
    categories: ["audio"],
    subcategory: "transcription",
    tags: ["AI", "speech-to-text", "open source", "transcription"],
    rating: 4.8,
    visits: 2500000,
    dateAdded: "2022-09-20",
    isPremium: 'Free',
  },
{
    name: "Podcastle",
    description: "All-in-one podcasting platform with AI voice cloning and editing features.",
    url: "https://podcastle.ai",
    id: "podcastle",
    image: "/tool-screenshots/podcastle.png",
    logo: "/logo/podcastle.png",
    categories: ["audio"],
    subcategory: "transcription",
    tags: ["AI", "podcasting", "voice cloning", "editing"],
    rating: 4.6,
    visits: 1000000,
    dateAdded: "2023-03-01",
    isPremium: 'Free',
  }
] 

export const mockTools = tools;